---
author:
    - name: S. Apartis
      orcid: 0000-0003-0140-1351
      affiliations:
      - ref: cis-cnrs

affiliations:
- id: cis-cnrs
  name: Centre national de la recherche scientifique
  department: Centre for Internet and Society
  city: Paris
  country: France
bibliography: references.bib
---

# Diversity {#diversity .unnumbered}

<div>

## History

| Version | Revision date | Revision    | Author        |
|---------|---------------|-------------|---------------|
| 1.0     | 2023-11-16    | First draft | Simon Apartis |

</div>

## Description

The concept of diversity draws attention to forms of diffused oppression and minorization processes and how they take place at a micro-political or even intimate scale, which are dimensions of social life that sometimes go unnoticed by a more macroscopic socio-economic inequality analysis framework. On the other hand, it tends to convey a depoliticized view of social inequalities by framing them as mere horizontal differences requiring *inclusion* rather than the product of power dynamics requiring *redistribution*\[1\].

The notion of diversity originated as a practical instrument introduced by Anglo-Saxon public policies in the 1980s, later followed by European policymakers and businesses. Despite the inherently positive connotation of the term "diversity," diversity strategies can also be analysed as paradoxical mechanisms of dominance, where a neutral Subject establishes marginalized groups as the "Other", strategizing ways to "include" this otherness, thereby reinforcing its exclusive authority in defining the Subject/Other dichotomy and the accompanying power dynamics\[2\].

That is why, in the effort to assess diversity, it is crucial to be careful about a few points. First, it is important to measure both socio-economic and societal aspects of diversity and think of them as a whole:

1.  Traditional socio-economic features such as income, wealth, education, employment rate, access to health services, housing conditions, and geographical inequalities
2.  And societal features such as gender identity, sexual orientation, religion or handicap

Second when it comes specifically to science, inequalities and diversity should be measured in three distinct aspects:

1.  Diversity in the topics of science (diversity as object / product of science)
2.  Diversity amongst the producers of science (diversity as subject/producer of science)
3.  Diversity in the methods of social production of science (diversity as mediating process between subject/producer and object/product)

Third, to measure diversity in science means to measure the role each participant plays at each stage of the scientific development\[3\]: design, development, data collection, processing, analysis, interpretation, dissemination, and ownership of results.

Last, it is important to look at the way the needs of diverse scholars participating to science are met and how much they are given the power to self-define them and the ways to have them met, for instance how latently or patently transphobic the work environment might be, or whether the scientific facilities are designed to be accessible with a wheelchair, etc.

One could also reflexively add that it is crucial in the very process of measuring diversity that the scientists who do it are themselves somehow diverse, and in any case, aware of specific tools they could use to control for the epistemological biases that comes with their situated position.

## Metrics

### Diversity in the topics of science

#/% of books, articles, thesis, research blogs, datasets or even piece of software related to or mentioning diversity topics

##### Existing datasourcesWeb of Science, Scopus, any Open Science Platform where the abstract or the full-text can be analysed to extract and clusterize the concepts and topics of the resourcesExisting methodologies

Scientometry, NLP

Note that this metrics supposes to have clearly defined what “diversity related topics” are, which is not easy to do.

### Diversity amongst the producers of science

-   #/% of queer / handicapped / female / racialized researcher who (co-)authored a book, article, thesis, research blog, dataset or a piece of software
-   Income and wealth level, access to health services, housing conditions, geographical location of the author(s) of a book, article, thesis, research blog, dataset or a piece of software
-   Same aforementioned features but broken down by scientific process step (design, development, data collection, processing, analysis, interpretation, dissemination, and ownership of results)

##### Existing datasources

Many of these data are considered sensitive by GDPR [@whatper], and very often, as a result of a very lack of diversity, the categories needed to measure diversity in existing datasets are lacking or follow normative principles that fail at representing and capturing diversity [@guyan2022].

##### Existing methodologies

Semi-structured survey

### Diversity in the mode of production of science

-   #/% of books, articles, thesis, research blogs, datasets or pieces of software produced in a research context where significant effort is made to include participants from diverse backgrounds
-   #/% of books, articles, thesis, research blogs, datasets or pieces of software generated in a research context where participants from diverse backgrounds have the agency to address their unique needs.
-   #/% of books, articles, thesis, research blogs, datasets or even piece of software authored by authors who frequently co-publish articles with participants from diverse backgrounds

##### Existing datasources

See previous.

##### Existing methodologies

This metrics supposes to have clearly defined what the specific needs of people from diverse backgrounds are.

1.  Notes

The academic field is characterized by certain set of subnorms that define a specific scientific ethos. Without settling immense debate of defining those norms, it is important to note that this specific ethos has implications for how diversity functions in and on science. Complying to the scientific ethos, in order to be able to “play the game of science” requires specific socio-economic conditions such as stable income, decent housing, access to higher education etc. that enable individuals to acquire the set of scientific skills needed to produce scientifically valid statements, that is to say peer recognized and compliant to scientific discursive norms.

The socio-economic preconditions of this "scholastic view" [@bourdieu2000], may act as a barrier for the underprivileged. Conversely, a series of paradigm shifts in the history, sociology, and philosophy of science (Kuhn, Longino, Wylie) has demonstrated that science is more infused with social values and hierarchies than previously believed and stressed out the fact that well-orchestrated diversity in research communities could lead to more efficient and scientifically relevant research. Last, it is important to note that in recent years, policymakers have implemented initiatives mandating that science take a more direct role in confronting immediate and urgent societal challenges; “Science with and for society” subprogram in the Horizon 2020 2014-2021 Program, followed by the full integration of the Responsible Research and Innovation principles in the 2021-2027 Horizon Europe Program.