# &lt;indicator name&gt; {#indicator-name .unnumbered}

History (please fill out in reverse chronological order, latest revision on top):

|         |               |                              |                           |
|---------|---------------|------------------------------|---------------------------|
| Version | Revision date | Revision                     | Author                    |
| 1.0     | 2023-02-07    | Finalised indicator template | T.P. Willemse, V.A. Traag |

## Description

There is an extensive scientometric literature on indicators of interdisciplinarity. However, the level of agreement among the various indicators introduced in the literature turns out to be low ([Wang & Schneider, 2020](https://doi.org/10.1162/qss_a_00011)). This appears to be the result of both different understandings of the concept of interdisciplinarity and different approaches to operationalize the concept. Given the lack of agreement on how to understand and operationalize interdisciplinarity, we advise against the use of scientometric indicators of interdisciplinarity, and we consequently do not describe any such indicators. For further discussion, including alternative approaches to 'measure' interdisciplinarity, we refer to [Rafols (2020)](https://www.leidenmadtrics.nl/articles/on-measuring-interdisciplinarity-from-indicators-to-indicating).

## Metrics

### &lt;metric name&gt;

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

## Known correlates

\[Add text here\]

## Notes

\[Add text here\]

## References

\[Add Zotero bibliography here\]
