---
author:
    - name: T. Venturini
      orcid: 0000-0003-0004-5308
      affiliations:
      - ref: cis-cnrs
      - ref: ugen

affiliations:
- id: cis-cnrs
  name: Centre national de la recherche scientifique
  department: Centre for Internet and Society
  city: Paris
  country: France
- id: ugen
  name: University of Geneva
  city: Geneva
  country: Switzerland
---

# Extra-academic collaborations {#extra-academic-collaborations .unnumbered}

::: {}

## History

| Version | Revision date | Revision    | Author       |
|---------|---------------|-------------|--------------|
| 1.0     | 2023-11-15    | First Draft | T. Venturini |

:::

## Description

This family of indicators is meant to assesses the degree to open science projects fosters and are supported by collaborations with *actors outside the academia* – and in particular with

1.  Civil society organisations
2.  Industrial and commercial enterprises
3.  Media and news organisations
4.  Public institutions

This family of indicators does *not* refer to the many ways in which the results of OS can be exploited, picked up or otherwise influence the activities of these non-academic actors. While these are most important phenomena, they are already covered by the indicators describing the societal and economic impacts of OS. Here, we also do not focus on the ways in which citizens contribute directly (as individuals) to the collection, analysis or dissemination of OS, since those dynamics are covered in the “citizen science indicators”.

Instead, this family of indicators focus specifically on tracing how the four different types of organisations listed above intervene in the production of OS, by providing different types of resources and specifically:

1.  Scientific or intellectual advice
2.  Access to data and/or field work opportunities
3.  Computational or human assistance in data treatment (cleaning, analysis, etc.)
4.  Direct funding or indirect economic aid
5.  Logistical, legal or commercial support for marketing or publication
6.  Other types of resources

## Existing datasources

The six types of collaborations listed above are not all equally easy to assess and quantify. Indeed, different types of extra-academic collaborations tend to be credited in scientific production in four main ways:

1.  by having non-academic organisations (or their members) to sign the publications (papers, conference proceedings, deliverables, reports, etc.) generated through the collaborations;
2.  by making explicit which person or which institutions did what part of the research in a project proposal or project reporting document;
3.  by declaring the amount of funding that was provided or received by the non-academic partners, as well as the financial equivalent of the resources they committed to or obtained by them through the collaboration;
4.  by recognizing the contributions provided by extra-academic partners through some form of written acknowledgment.

Clearly, these four types do not cover the six types of collaborations in a one-to-one way. Authoring a paper can indeed be a marker for any type of involvement in a research and non-financial contributions are sometimes declared by translating them into their financial equivalent – though they not always are. Finally, written acknowledgments are often used to declare collaborations, but their format is not standardized. This means that all the three metrics described below should be accompanied with some qualitative investigation necessary to untangle the different types of collaborations that the same quantity can erroneously lump together.

### Extra-academic authorship

Considering the signatures of the authors of scientific publications and the affiliations attached to those signatures is often the most straightforward way of detecting whether members of non-academic organisations have collaborated on a scientific project. Most forms of scientific publication (books, papers, conferences proceedings, book chapters, etc.) are signed and signed not only with the names of their authors, but also with the name of the organisations to which these authors belong.

Signature affiliations have been used in all sorts of bibliometric research to measure the diversity or homogeneity of the authorship of a given piece of research – by considering, for instance, the geographical or disciplinary spread of the author teams. A similar approach can and has been used to assess which authors of a publication all come from within or beyond the Academia. While such a decision may seem easy, however, it actually entails many ambiguities and difficulties. For one thing, authors often sign with multiple affiliations, and it is not always clear which one is relevant in each situation. People can sign with the name of a given organisation because they want to acknowledge their belonging to it even if they participated in the research under consideration as private individuals or under the aegis of other organisations. Similarly, the distinction between academic and non-academic organisation is not always clear-cut and some research groups can be categorized differently according to different definitions of societal sectors. Finally knowing that someone from a given organisation has signed a given publication tells us that they have contributed to the associated research but not in which precise way.

### Extra-academic authorship

Signatures are not the only way to assess research authorship. Research that went through a formal process of pre- or post-evaluation are generally carefully described either in the *ex-ante* proposal that describe the plan of the research or (even better) in the ex-post reporting documents that illustrate the work that has been done. These documents, when available, can be extremely useful not only to have a precise sense of who has done what in the research, but also to estimate to what extent the collaboration has been fruitful. Unfortunately, however, this type of document is generally only available for the largest most institutionalized projects and smaller research endeavors might not be subjected to this type of reporting. Even when these documents exist, they are sometimes only available to the funding institutions, but not made public because of questions of confidentiality. Finally, proposals and intermediary of final reports rarely follow standard formats, which makes it difficult to examine them quantitatively and on a large scale (though close qualitative reading can provide extremely interesting insights).

### Funding to or from extra-academic organisations

We described above how research reporting documents can be useful to investigate collaboration, be them within the academia or beyond its boundaries. We also notice, however, that these documents are not always accessible to investigation. Among them the most frequently available type of reporting document are budgets. Funding records often contains cues about the different contributions that supported a given research. Some budgets contain even the precise dates at which the expenses were made, and the type of expense carried out. This typology of expenses is generally relatively standard, distinguishing between direct and indirect costs, personnel, travel, data acquisition, subcontracting, equipment, etc. Furthermore, budgets come with an inherent quantification, offered by the very effort of “monetization” intrinsic to this accounting exercise. Of course, monetary quantities are neither the only nor the most important measures of scientific effort, yet they can sometime offer an interesting albeit very partial proxy of it.

### Acknowledgment of extra-academic support

Finally, scientific publications (be them academic papers, popularization pieces, research blogs) often come with some form of acknowledgments or credits describing the different contributions given to a project, and especially the contributions coming from outside academia. This type of information is the richest of the ones considered in this document, but also the least standardized. However, if researchers can find the time and the patience to consider these acknowledgments qualitatively and manually annotate them, they can provide a mine of information for investigating collaborations across and beyond the Academia.

## Metrics

The four types of non-academic organisations and the six types of possible collaboration introduced in the “description” section design a matrix of indicator that one can take into consideration in investigating how scientific research is supported by external partnerships:

+-----------+-----------+-----------+-----------+-----------+-----------+
|           | Civil     | I         | Media and | Public    | **Total   |
|           | society   | ndustrial | news      | ins       | by type   |
|           | orga      | &         | orga      | titutions | of        |
|           | nisations | c         | nisations |           | collab    |
|           |           | ommercial |           |           | oration** |
|           |           | en        |           |           |           |
|           |           | terprises |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+
| S         |           |           |           |           |           |
| cientific |           |           |           |           |           |
| or        |           |           |           |           |           |
| inte      |           |           |           |           |           |
| llectual\ |           |           |           |           |           |
| advice    |           |           |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+
| Access to |           |           |           |           |           |
| data      |           |           |           |           |           |
| and/or    |           |           |           |           |           |
| field     |           |           |           |           |           |
| work      |           |           |           |           |           |
| oppo      |           |           |           |           |           |
| rtunities |           |           |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+
| Comp      |           |           |           |           |           |
| utational |           |           |           |           |           |
| or human  |           |           |           |           |           |
| a         |           |           |           |           |           |
| ssistance |           |           |           |           |           |
| in data   |           |           |           |           |           |
| treatment |           |           |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+
| Direct    |           |           |           |           |           |
| funding   |           |           |           |           |           |
| or        |           |           |           |           |           |
| indirect  |           |           |           |           |           |
| economic  |           |           |           |           |           |
| aid       |           |           |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+
| Lo        |           |           |           |           |           |
| gistical, |           |           |           |           |           |
| legal or  |           |           |           |           |           |
| c         |           |           |           |           |           |
| ommercial |           |           |           |           |           |
| support   |           |           |           |           |           |
| for       |           |           |           |           |           |
| marketing |           |           |           |           |           |
| or        |           |           |           |           |           |
| pu        |           |           |           |           |           |
| blication |           |           |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+
| Other     |           |           |           |           |           |
| forms of  |           |           |           |           |           |
| colla     |           |           |           |           |           |
| borations |           |           |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+
| **Total   |           |           |           |           |           |
| by type   |           |           |           |           |           |
| of        |           |           |           |           |           |
| collab    |           |           |           |           |           |
| oration** |           |           |           |           |           |
+-----------+-----------+-----------+-----------+-----------+-----------+

The data sources described in the previous section can be used to populate this double entry table for a given piece of research, a set of researches or (even more interestingly) several sets of researches whose different collaboration-profile can be assessed comparing their value for each of the cell, row or column as well as for the entire table.

In particular, all the metrics matrix and the data source described above can be employed to assess collaboration in OS but also in non-OS projects, allowing to investigate whether open science is less or more prone to facilitate specific types of collaboration. Similarly, the comparison can be carried out by disciplinary field, type of research, project size or duration, type of funding, etc.
