---
author:
    - name: L. Waltman
      orcid: 0000-0001-8249-1752
      affiliations:
      - ref: cwts

affiliations:
- id: cwts
  name: Leiden University
  department: Centre for Science and Technology Studies
  city: Leiden
  country: the Netherlands

title: Interdisciplinary and novelty
---


::: {.callout collapse="true"}


# History

| Version | Revision date | Revision    | Author     |
|---------|---------------|-------------|------------|
| 1.1     | 2023-12-17    | Add novelty | L. Waltman |
| 1.0     | 2023-12-17    | First draft | L. Waltman |

:::

# Description

There is an extensive scientometric literature on indicators of interdisciplinarity, novelty, and other related concepts. However, the level of agreement among the various indicators introduced in the literature turns out to be low [@wang2020]. This appears to be the result of both different understandings of the concepts such as interdisciplinarity and novelty and different approaches to operationalize these concepts [@fontana_new_2020]. Given the lack of agreement on how to understand and operationalize the concepts of interdisciplinarity and novelty, we advise against the use of scientometric indicators of interdisciplinarity and novelty, and we consequently do not describe any such indicators. For further discussion, including alternative approaches to 'measure' interdisciplinarity, we refer to [@ràfols2020].
