---
author:
    - name: V.A Traag
      orcid: 0000-0003-3170-3879
      affiliations:
      - ref: cwts

affiliations:
- id: cwts
  name: Leiden University
  department: Centre for Science and Technology Studies
  city: Leiden
  country: the Netherlands

title: Introduction to academic impact
---


::: {.callout collapse="true"}


## History

| Version | Revision date | Revision    | Author     |
|---------|---------------|-------------|------------|
| 1.0     | 2024-12-06    | First draft | V.A. Traag |

:::

Of the various areas of impact (academic, societal and economic) of Open Science, academic impact is probably the most well-established and researched impact area. In particular, indicators of [citation impact](citation_impact.qmd) and [collaborations](collaboration_intensity.qmd) have a long history and a long development and are well-established. At the same time, there are also more recently developed indicators that are becoming relevant in this area, such as the [reuse of data](reuse_of_data_in_research.qmd) and [code](reuse_of_code_in_research.qmd) in research, and are still actively being developed. The rise of reference managers enabled tracking [readership](academic_readership.qmd) instead of only citations, making it possible to distinguish between papers that are read widely and papers that are cited widely. At the same time, aspects of academic impact such as “quality”, [“novelty” or “interdisciplinarity”](interdisciplinarity.qmd) remain complicated to develop robust indicators for based on existing data sources, thus requiring more in-depth manual assessments.

In addition, academic impact is most closely associated with Open Science practices, meaning that we can track potential effects of Open Science more easily than in societal and academic impact. This is also visible in the available literature on specific impacts. For instance, the PathOS’ scoping review of academic impact [@klebel_academic_2024] lists 489 studies compared to 196 reviewed studies in societal impact [@cole_societal_2024], and even less for economic impact. There is also a streetlight effect, with studies of the impact of Open Access on Citation Advantage constituting a large part of the literature on academic impact.

Still, although establishing a connection between Open Science and academic impact is more straightforward, inferring the causal effect remains a common challenge across impact areas.