project:
  type: book
  output-dir: _book
  execute-dir: project

book:
  title: Open Science Indicator Handbook
  reader-mode: true

  site-url: https://handbook.pathos-project.eu/
  repo-url: https://github.com/PathOS-project/indicator_handbook/
  repo-branch: main
  repo-actions: [edit, issue]

  downloads: [docx]

  navbar:
    search: true
    logo: theme/pathos-logo.png
    logo-href: https://pathos-project.eu/

  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd

    # - causal_intro/article/intro-causality.qmd Skip causal intro for now

    - part: Open Science
      chapters:
        - indicator_templates/quarto/1_open_science/APC_costs.qmd
        - indicator_templates/quarto/1_open_science/availability_data_repositories.qmd
        - indicator_templates/quarto/1_open_science/availability_preprint_repositories.qmd
        - indicator_templates/quarto/1_open_science/availability_publication_repositories.qmd
        - indicator_templates/quarto/1_open_science/citizen_science.qmd
        - indicator_templates/quarto/1_open_science/deposition_open_metadata.qmd
        - indicator_templates/quarto/1_open_science/evaluation_open_science_in_research_assessment.qmd
        - indicator_templates/quarto/1_open_science/open_access_journals.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_access_publishing.qmd
        - indicator_templates/quarto/1_open_science/open_science_training_facilities.qmd
        - indicator_templates/quarto/1_open_science/prevalence_national_open_science_policies.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_fair_data_practices.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_method_practices.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_peer_review.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_science_funding_policies.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_science_support.qmd
        - indicator_templates/quarto/1_open_science/prevalence_preprinting.qmd
        - indicator_templates/quarto/1_open_science/prevalence_replication_studies.qmd
        - indicator_templates/quarto/1_open_science/transformative_publishing_agreements.qmd

    - part: Academic Impact
      chapters:
        - indicator_templates/quarto/2_academic_impact/academic_readership.qmd
        - indicator_templates/quarto/2_academic_impact/citation_impact.qmd
        - indicator_templates/quarto/2_academic_impact/collaboration_intensity.qmd
        - indicator_templates/quarto/2_academic_impact/diversity.qmd
        - indicator_templates/quarto/2_academic_impact/extra-academic_collaboration.qmd
        - indicator_templates/quarto/2_academic_impact/interdisciplinarity.qmd
        - indicator_templates/quarto/2_academic_impact/novelty.qmd
        - indicator_templates/quarto/2_academic_impact/use_of_code_in_research.qmd
        - indicator_templates/quarto/2_academic_impact/use_of_data_in_research.qmd

    - part: Societal Impact
      chapters:
        - indicator_templates/quarto/3_societal_impact/uptake_and_impact_on_societal_issues.qmd
        - indicator_templates/quarto/3_societal_impact/uptake_by_media.qmd
        - indicator_templates/quarto/3_societal_impact/scientific_literacy.qmd
        - indicator_templates/quarto/3_societal_impact/uptake_by_policy_makers.qmd

    - part: Economic Impact
      chapters:
        - indicator_templates/quarto/4_economic_impact/science_industry_collaboration.qmd
        - indicator_templates/quarto/4_economic_impact/innovation_output.qmd
        - indicator_templates/quarto/4_economic_impact/socially_relevant_products_and_processes.qmd
        - indicator_templates/quarto/4_economic_impact/economic_growth_of_companies.qmd
        - indicator_templates/quarto/4_economic_impact/labour_market_impacts.qmd
        - indicator_templates/quarto/4_economic_impact/cost_savings.qmd

    - part: Reproducibility
      chapters:
        - reproducibility_intro.qmd
        - indicator_templates/quarto/5_reproducibility/consistency_in_reported_numbers.qmd
        - indicator_templates/quarto/5_reproducibility/impact_of_open_code_in_research.qmd
        - indicator_templates/quarto/5_reproducibility/impact_of_open_data_in_research.qmd
        - indicator_templates/quarto/5_reproducibility/inclusion_in_systematic_reviews_or_meta-analyses.qmd
        - indicator_templates/quarto/5_reproducibility/level_of_replication.qmd
        - indicator_templates/quarto/5_reproducibility/polarity_of_publications.qmd
        - indicator_templates/quarto/5_reproducibility/reuse_of_code_in_research.qmd
        - indicator_templates/quarto/5_reproducibility/reuse_of_data_in_research.qmd

comments:
  hypothesis:
    theme: clean

format:
  html:
    theme:
      - cosmo
      - theme/style.scss
    code-link: true
    grid:
      sidebar-width: 350px

    author-meta: "V.A. Traag, etc..."
    callout-appearance: simple

  docx:
    reference-doc: theme/template.docx

editor: visual