---
author:
    - name: I. Grypari
      orcid: 0000-0002-7485-1591
      affiliations:
      - ref: arc
    - name: N. Manola
      orcid: 0000-0002-3477-3082
      affiliations:
      - ref: arc
    - name: H. Papageorgiou
      orcid: 0000-0002-7352-2403
      affiliations:
      - ref: arc
    - name: P. Stavropoulos
      orcid: 0000-0003-1664-6554
      affiliations:
      - ref: arc

affiliations:
- id: arc
  name: Athena Research Center
  city: Athena
  country: Greece
bibliography: references.bib
---

# APC Costs {#apc-costs .unnumbered}

<div>

## History

| Version | Revision date | Revision | Author |
|-------------|-------------|---------------|-------------------------------|
| 1.1 | 2023-08-28 | Draft for initial publication | I. Grypari |
| 1.0 | 2023-05-09 | First draft | I. Grypari, N. Manola, H. Papageorgiou, P. Stavropoulos |

</div>

## Description

Αrticle Processing Charges (APCs) represent the price that publishers demand from authors to pay in order to publish their articles and books under an open access license. They capture the affordability and accessibility of Open Access publishing for different types of stakeholders, such as researchers, institutions, and funding agencies. It is also relevant for policy-makers seeking to optimize Open Science policies.

Tracking and comparing APCs could also be used to encourage publishers to adopt more transparent and equitable pricing policies and support the development of sustainable Open Access publishing models accessible to all researchers regardless of their financial resources.

APCs have both benefits and drawbacks. In a strict sense, they do not remove the economic barriers between the writing and the reading of scientific results but shift these costs from the readers to the authors. In countries where funder reimbursement of APC costs or transformative agreements do not cover these costs, APCs can create a financial barrier that limits access to Open Access journals, often generating asymmetries between richer and poorer countries and academic institutions. On the other hand, APCs also incentivize publishers to offer Open Access publishing, which promotes Open Science.

## Metrics

### Number/Share (%) of publications with an APC cost

These metrics measure the number or share (in percentage - %) of publications in journals and have incurred an APC. The share provides a more nuanced understanding of the affordability and accessibility of Open Access publishing than the absolute number and it can be used to compare the affordability and accessibility of Open Access publishing across different journals, publishers, and regions in a more meaningful way.

Limitation:

-   Not knowing who incurred that APC (funder, institution, author, etc.) limits the usefulness of this indicator.
-   The share of publications with an APC could be more useful when put together with % Diamond OA publications, as opposed to stand alone.

#### Measurement.

##### Methodology

###### OpenAIRE Graph

The [OpenAIRE Graph](https://graph.openaire.eu) dump currently does not include OA color classifications, though they are already implemented in the OpenAIRE MONITOR and are expected to be integrated into the graph dump in Q1 2024.

1.  Retrieve all Gold OA publications from OpenAIRE, which refers to those published in entirely OA journals. Exclude those classified as Diamond OA (meaning they don't have an APC). The publications left in this group are Gold OA articles with associated APCs.
2.  Incorporate Hybrid and Bronze OA publications to this set, as these also come with APCs.
3.  Cross-reference the APCs listed in OpenAIRE, sourced from OpenAPC (openapc.net), to ensure no additional articles with APCs are overlooked.
4.  Using this refined set of OA publications with APCs, determine the number or share based on your specific area of interest (e.g., country).

Limitations:

-   This methodology is a workaround chosen as it provides better coverage than any APC dataset we are aware of, however it is not a direct source of whether a publication has incurred an APC or not.

### Average APC

Description:

The "average APC" metric measures the average cost of Article Processing Charges (APCs) across a defined level of interest (per year, country, organization, etc.).

Usefulness:

The "average APC" metric can help assess the affordability and accessibility of Open Access publishing. It provides a broad understanding of the cost of Open Access publishing and identifies trends and changes in APC pricing over time. This metric can help researchers, institutions, and funding agencies to compare the cost-effectiveness of different Open Access publishing models and identify affordable publishing options.

Limitations:

-   The cost of APCs can vary widely depending on the field of research, the region, and the specific publisher or journal, therefore taking an average may be misleading.
-   Not knowing who incurred that APC (funder, institution, author, etc.) limits the usefulness of this metric.

#### Measurement.

##### Datasources

###### OpenAIRE Graph

The OpenAPC APC dataset, which is integrated in the [OpenAIRE Graph](https://graph.openaire.eu).

Limitations:

-   Incomplete data: Publishers do not generally provide data on their APC fees, OpenAPC (openapc.net) has a growing collection but it is not complete.
-   In an (organization, publication, APC cost) triplet of OpenAPC, to the best of our knowledge, it is not possible to distinguish if the APC cost is the entire cost of the publication or just the what the organization paid.

##### Methodology

Via OpenAIRE MONITOR (monitor.openaire.eu)

1.  Identify the unit of analysis (e.g. average APCs for an institution)
2.  Examine the coverage of APCs for the relevant publications (see metric Number of OA publications with APC).
3.  Examine if the coverage is adequate and the distribution of costs meaningful for taking an average.
4.  Take the average APC for that level of analysis.

Limitations:

-   Averages have the benefit of summarizing and normalizing information, however depending on the underlying distribution of costs, they may be misleading (e.g. via outliers)

### Total APC

Description:

The "Total APC" metric measures the sum of APCs paid for all the articles published for a defined level of interest (a year, country, organization, etc.)

Usefulness:

-   The "total APC" metric can help assess the affordability and accessibility of Open Access publishing. It provides a broad understanding of the cost of Open Access publishing and identifies trends and changes in APC pricing over time. By summing the APCs this metric measures the total financial burden of OA publishing for the unit of analysis and can be compared to other aggregate measures.

Limitations:

-   Not knowing who incurred that APC (funder, institution, author, etc.) limits the usefulness of this metric, more than the previous ones.
-   It does not contain information of the distribution of APCs across a subdomain, e.g. Total cost does not give info on how it is distributed across scientific domains.

#### Measurement.

##### Datasources

###### OpenAIRE Graph

The OpenAPC APC dataset, which is integrated in the [OpenAIRE Graph](https://graph.openaire.eu).

Limitations:

-   Incomplete data: Publishers do not generally provide data on their APC fees, OpenAPC (openapc.net) has a growing collection but it is not complete.
-   In an (organization, publication, APC cost) triplet of OpenAPC, to the best of our knowledge, it is not possible to distinguish if the APC cost is the entire cost of the publication or just the what the organization paid.

##### Methodology

Via OpenAIRE MONITOR

1.  Identify the unit of analysis (e.g. total APCs for an institution)
2.  Examine the coverage of APCs for the relevant publications (see metric Number of OA publications with APC).
3.  Examine if the coverage is adequate.
4.  Sum the APCs for that level of analysis.

Limitations:

-   Totals have the benefit of giving a bird's eye view, however depending on the underlying distribution of costs, they can have different implications.

## Known correlates

Via: <https://direct.mit.edu/qss/article/1/1/6/15582/Article-processing-charges-Mirroring-the-citation>

-   Year
-   Publisher
-   Hybrid vs. Gold OA
-   SNIP

### Estimating unknown APCs

An APC extrapolation exercise was conducted for the purpose of an EC study [@monitori2021]. The authors defined groupings, and imputed the average APC of the group to each publication in the group for which the APC is unknown. The groupings were based on the following variables, similar to the correlates above: - quantile of the Source Normalised Impact per Paper (SNIP) score in the [CWTS journal indicators](https://www.journalindicators.com/), - whether the publication is pure ‘gold’ open access or ‘hybrid’, - the year of publication.

The [French Open Science Monitor](https://frenchopensciencemonitor.esr.gouv.fr/) also uses several extrapolations when the APC for a DOI is not available in OpenAPC [@bracco2022]. They are listed here in order of preference (only when one computation is not possible is the following used): - average APC for the same journal and the same year in OpenAPC (provided $n \geq 10$) - average APC for the same publisher in OpenAPC, for the same year as the article (provided $n \geq 10$) - average APC for the same journal in OpenAPC, for all years available - average APC for the same publisher in OpenAPC, for all years available - APC for the journal in DOAJ.