---
author:
    - name: I. Grypari
      orcid: 0000-0002-7485-1591
      affiliations:
      - ref: arc
    - name: N. Manola
      orcid: 0000-0002-3477-3082
      affiliations:
      - ref: arc
    - name: H. Papageorgiou
      orcid: 0000-0002-7352-2403
      affiliations:
      - ref: arc
    - name: P. Stavropoulos
      orcid: 0000-0003-1664-6554
      affiliations:
      - ref: arc

affiliations:
- id: arc
  name: Athena Research Center
  city: Athena
  country: Greece
---

# Availability of pre-print repositories {#availability-of-pre-print-repositories .unnumbered}

History (please fill out in reverse chronological order, latest revision on top):

| Version | Revision date | Revision    | Author                                                  |
|---------|---------------|-------------|---------------------------------------------------------|
| 0.1     | 2023-05-9     | First draft | I. Grypari, N. Manola, P. Stavropoulos, H. Papageorgiou |

## Description

Description:

-   The "availability of preprint repositories" indicator measures the availability and accessibility of preprint repositories that are available to researchers in a particular level of interest such as field, country or organization.

Usefulness:

-   The "availability of preprint repositories" indicator provides insight into the infrastructure and resources available to researchers for sharing their work as preprints.
-   It can help to identify areas where preprint repositories are lacking or where access to these repositories is limited, potentially hindering the adoption of preprinting practices.
-   This indicator can also be used to assess the impact of preprint repositories on scholarly communication and to identify areas where additional resources and support may be needed.

Limitations:

-   Not all fields or research areas may have a culture of preprinting, which can affect the applicability of the indicator in different contexts.
-   There may be good preprint practices in general repositories (such as Zenodo) that would not be identifiable via this indicator.

## Metrics

### Number of preprint repositoriesW

Description:

-   The "number of preprint repositories" indicator measures the quantity of preprint repositories available to researchers in a particular field, country, organization, etc.

Usefulness:

-   See indicator description.

Limitations:

-   See indicator description.

#### Measurement.

Count

##### Datasources

######  ASAPbio

ASAPbio maintains a list of preprint repositories, available from https://asapbio.org/preprint-servers.

## Known correlates

We do not know for sure but we assume the following:

1.  Scientific field
2.  Country (better OS infrastructure?)

## References

\[Add Zotero bibliography here\]
