---
author:
    - name: I. Grypari
      orcid: 0000-0002-7485-1591
      affiliations:
      - ref: arc
    - name: N. Manola
      orcid: 0000-0002-3477-3082
      affiliations:
      - ref: arc
    - name: H. Papageorgiou
      orcid: 0000-0002-7352-2403
      affiliations:
      - ref: arc
    - name: P. Stavropoulos
      orcid: 0000-0003-1664-6554
      affiliations:
      - ref: arc

affiliations:
- id: arc
  name: Athena Research Center
  city: Athena
  country: Greece
---

# Distribution of Open Access journal models {#distribution-of-Open-Access-journal-models .unnumbered}

::: {}

## History

| Version | Revision date | Revision                      | Author                                                  |
|---------|---------------|-------------------------------|---------------------------------------------------------|
| 1.1     | 2023-05-09    | Draft for initial publication | I. Grypari                                              |
| 1.0     | 2023-05-09    | First Draft                   | N. Manola, I. Grypari, H. Papageorgiou, P. Stavropoulos |

:::

## Description

Description:

-   This indicator offers a comprehensive view of the diversity and prevalence of different open access publishing models in a specified research domain, whether regional, national, or subject-specific. It differentiates journal business model along two dimension.

**Access rights of Articles:**

-   -   Fully OA Journal: All articles are OA
    -   Hybrid Journal: Some articles are OA some not.
    -   Subsciption Journal (remaining)

**APC costs of OA Articles:**

-   -   Diamond OA Journal: Fully OA journal without APCs.
    -   Fully OA Journal with APCs (remaining)

Usefulness:

-   Provides a comprehensive view of the open access publishing ecosystem, showcasing how traditional and modern publishing models coexist.
-   Enables stakeholders to gauge the extent of OA adoption and the diversity of financial models supporting it.

Can inform policy decisions, grant funding requirements, and authors' publication choices by showcasing the prominence and availability of various OA modelsLimitations:

-   Solely quantitative; does not address the qualitative aspects of journals, such as their reputation, impact factor, or the quality of peer review.
-   Not all fields or research areas may have a culture of OA publishing, which can affect the comparison of the indicator across different contexts.
-   This indicator also does not account for other forms of OA publishing, such as OA monographs or book chapters, which can also play a role in the dissemination of research findings.

## Metrics

### Number/Share (%) of Fully OA Journals

Description:

Number/Share (%) of OA journals in a specific area of interest (e.g., country, subject, year)Usefulness:

-   Allows for comparison of Open publishing prevalence across different regions or fields of study.
-   Provides insights into the growth or decline of OA journals over time.
-   Proxy for research visibility as areas with a higher percentage of OA journals likely offer greater visibility and accessibility to research findings.
-   Can be used by institutions and funders to gauge the prevalence of OA platforms available to researchers in specific areas and adjust funding or publishing mandates accordingly.

Limitations:

- A sheer count or percentage doesn't give insights into the quality of the OA journals.

- Not all fields or research areas have a culture of OA publishing, which can skew comparisons.[]{#measurement.-14}Measurement.

Count or share.


#### Measurement.

##### Datasources

###### DOAJ (included in the OpenAIRE Graph)

Limitations:

-   While DOAJ is comprehensive, not all OA journals may be listed, especially if they are newer or have not met the DOAJ's criteria.

###### OpenAIRE Graph

##### Methodology

This methodology is taken from [OpenAIRE MONITOR](https://monitor.openaire.eu/methodology/terminology%22%20\l%20%22constructed-attributes) and uses the OpenAIRE Graph as the input database.

A journal is defined as fully Open Access if one or more of the following occur:

-   It is in the Directory of Open Access Journals (DOAJ)
-   It has a known fully OA Publisher (curated list that will be included in the OpenAIRE Graph in Q1 2024).
-   It only publishes OA articles.

### Number/Share (%) of Hybrid OA Journals

**A hybrid OA journal is a subscription journal where some of its articles are open access.**

Usefulness

-   Indicates the prevalence of journals that provide open access options without being fully open access.
-   Provides an understanding of how many journals offer a middle-ground approach to OA.

Limitations:

-   The metric may not capture the nuances of each hybrid journal's open access policies.
-   The prevalence of hybrid OA doesn't necessarily indicate the volume of OA content..

#### Measurement.

##### Datasources

###### OpenAIRE Graph

Count or take the share (%) of journals in OpenAIRE with open access articles that are not fully OA journals as defined in the previous metric.

### Number/Share (%) of Diamond OA Journals

A diamond OA journal is a fully OA journal that does not charge article processing charges (APCs). In other words the diamond OA journals are a subset of the fully Open Access journals (described in 10.3.1).

Usefulness

-   Provides insights into journals that are promoting open access without transferring the cost to authors. Indicates the prevalence of journals that provide open access options without being fully open access.
-   Can indicate a commitment to equitable knowledge dissemination in the academic publishing landscape.

Limitations:

-   Relying on APC data might not capture other potential costs or financial barriers associated with publishing in the journal.

#### Measurement.

##### Datasources

###### DOAJ

###### OpenAIRE Graph

Use APC data from DOAJ (integrated in the OpenAIRE Graph or using DOAJ's Public Data Dump - an exportable version of the journal metadata). Used it to determine whether a particular fully OA journal charges APCs.

