---
author:
    - name: I. Grypari
      orcid: 0000-0002-7485-1591
      affiliations:
      - ref: arc
    - name: N. Manola
      orcid: 0000-0002-3477-3082
      affiliations:
      - ref: arc
    - name: H. Papageorgiou
      orcid: 0000-0002-7352-2403
      affiliations:
      - ref: arc
    - name: P. Stavropoulos
      orcid: 0000-0003-1664-6554
      affiliations:
      - ref: arc

affiliations:
- id: arc
  name: Athena Research Center
  city: Athena
  country: Greece
---

# Prevalence of open method practices {#prevalence-of-open-method-practices .unnumbered}

::: {.callout-note collapse="true"}

## History

| Version | Revision date | Revision    | Author                                                  |
|---------|---------------|-------------|---------------------------------------------------------|
| 1.0     | 2023-02-12    | First draft | I. Grypari, N. Manola, H. Papageorgiou, P. Stavropoulos |

:::

## Description

“*Methods describe the processes, procedures, and materials used in a research investigation. Methods can take many forms depending on the field and approach, including study designs, protocols, code, materials and reagents, databases and more.”^[\[1\]](#footnote-2){#footnote-ref-2}^*

Open methods refer to:

1.  Open Access to the various elements of the scientific method (datasets, software/code, protocols, materials, etc.)
2.  FAIRness of the same elements (i.e. following the FAIR principles), and,
3.  an Open and FAIR documentation, that facilitates reproducibility and reuse of the study methods.

## Metrics

### Number/share of publications with Open Source code

**Description:** Number of publications with Open Source code: This is the number of publications for which the code that was developed in this context to produce the scientific outcomes included in the publication is shared/can be found with Open Access in open repositories.

**Benefits:** Providing Open Access to software/code of the scientific method is of key importance of understanding, evaluating, replicating and extending the study.

**Limitations:** In most cases, detailed documentation must accompany the code including data management, cleansing and pre-processing, configuration files and workflows.

**Differences:** ..?

#### Measurement.

There is no comprehensive list of publication-software pairs. The metric is partially covered by well-established repositories like GitHub or existing data sources like OpenAIRE. Automated approaches have been built (e.g., PapersWithCode) or are under development in the scientific community, scanning the publication text and spotting mentions of software/code and its FAIR metadata.

There is no well-established methodology to automatically find publications with code. Some suggested methods are the following:

1.  Text mining and machine learning algorithm to find mentions of open software/code and its FAIR metadata in the publication text.
2.  Search relevant fields or tags in specific databases to find publications with software/code.

## References

1.  ::: {#footnote-2}
    https://plos.org/open-science/open-methods/ [↑](#footnote-ref-2)
    :::
