DIR1="edits"
DIR2="../indicator_templates/quarto/"

# cp ${DIR1}/000-unnamed.md
# cp ${DIR1}/abbreviations.md
cp ${DIR1}/academic-readership.md ${DIR2}/2_academic_impact/academic_readership.qmd
cp ${DIR1}/apc-costs.md ${DIR2}/1_open_science/APC_costs.qmd
cp ${DIR1}/availability-of-data-repositories.md ${DIR2}/1_open_science/availability_data_repositories.qmd
cp ${DIR1}/availability-of-preprint-repositories.md ${DIR2}/1_open_science/availability_preprint_repositories.qmd
cp ${DIR1}/availability-of-publication-repositories.md ${DIR2}/1_open_science/avail.qmd
cp ${DIR1}/citation-impact.md ${DIR2}/2_academic_impact/citation_impact.qmd
cp ${DIR1}/citizen-science-indicators.md ${DIR2}/1_open_science/citizen_science.qmd
cp ${DIR1}/collaboration-intensity.md ${DIR2}/2_academic_impact/collaboration_intensity.qmd
cp ${DIR1}/consistency-in-reported-numbers.md ${DIR2}/5_reproducibility/consistency_in_reported_numbers.qmd
cp ${DIR1}/cost-savings.md ${DIR2}/4_economic_impact/cost_savings.qmd
cp ${DIR1}/deposition-of-open-metadata.md ${DIR2}/1_open_science/deposition_open_metadata.qmd
# cp ${DIR1}/disclaimer.md
cp ${DIR1}/distribution-of-open-access-journal-models.md ${DIR2}/1_open_science/open_access_journals.qmd
cp ${DIR1}/diversity.md ${DIR2}/2_academic_impact/diversity.qmd
cp ${DIR1}/economic-growth-of-companies.md ${DIR2}/4_economic_impact/economic_growth_of_companies.qmd
cp ${DIR1}/effect-on-democracy.md ${DIR2}/3_societal_impact/effect_on_democracy.qmd
cp ${DIR1}/effect-on-ethnic-inequality.md ${DIR2}/3_societal_impact/effect_on_ethnic_inequality.qmd
cp ${DIR1}/effect-on-gender-inequality.md ${DIR2}/3_societal_impact/effect_on_gender_inequality.qmd
cp ${DIR1}/effect-on-sdgs.md ${DIR2}/3_societal_impact/effect_on_sdgs.qmd
cp ${DIR1}/evaluation-of-open-science-in-research-assessment.md ${DIR2}/1_open_science/evaluation_open_science_in_research_assessment.qmd
# cp ${DIR1}/executive-summary.md
cp ${DIR1}/impact-of-open-code-in-research.md ${DIR2}/5_reproducibility/impact_of_open_code_in_research.qmd
cp ${DIR1}/impact-of-open-data-in-research.md ${DIR2}/5_reproducibility/impact_of_open_data_in_research.qmd
cp ${DIR1}/inclusion-in-systematic-reviews-or-meta-analyses.md ${DIR2}/5_reproducibility/inclusion_in_systematic_reviews_or_meta-analyses.qmd
cp ${DIR1}/industry-collaboration.md ${DIR2}/2_academic_impact/industry_collaboration.qmd
cp ${DIR1}/innovation-output.md ${DIR2}/4_economic_impact/innovation_output.qmd
cp ${DIR1}/interdisciplinarity.md ${DIR2}/2_academic_impact/interdisciplinarity.qmd
# cp ${DIR1}/introduction.md
cp ${DIR1}/labour-market-impacts.md ${DIR2}/4_economic_impact/labour_market_impacts.qmd
cp ${DIR1}/level-of-replication.md ${DIR2}/5_reproducibility/levels_of_replication_found.qmd
cp ${DIR1}/novelty.md ${DIR2}/2_academic_impact/novelty.qmd
cp ${DIR1}/open-science-training-facilities.md ${DIR2}/1_open_science/open_science_training_facilities.qmd
cp ${DIR1}/polarity-of-publications.md ${DIR2}/5_reproducibility/polarity_of_publications.qmd
cp ${DIR1}/prevalence-of-national-open-science-policies.md ${DIR2}/1_open_science/prevalence_national_open_science_policies.qmd
cp ${DIR1}/prevalence-of-open-access-publishing.md ${DIR2}/1_open_science/open_access_uptake.qmd
cp ${DIR1}/prevalence-of-open-fair-data-practices.md ${DIR2}/1_open_science/prevalence_open_fair_data_practices.qmd
cp ${DIR1}/prevalence-of-open-method-practices.md ${DIR2}/1_open_science/prevalence_open_method_practices.qmd
cp ${DIR1}/prevalence-of-open-peer-review.md ${DIR2}/1_open_science/prevalence_open_peer_review.qmd
cp ${DIR1}/prevalence-of-open-science-funding-policies.md ${DIR2}/1_open_science/prevalence_open_science_funding_policies.qmd
cp ${DIR1}/prevalence-of-open-science-support.md ${DIR2}/1_open_science/prevalence_open_science_support.qmd
cp ${DIR1}/prevalence-of-preprinting.md ${DIR2}/1_open_science/prevalence_preprinting.qmd
cp ${DIR1}/prevalence-of-replication-studies.md ${DIR2}/1_open_science/prevalence_replication_studies.qmd
cp ${DIR1}/reuse-of-code-in-research.md ${DIR2}/5_reproducibility/reuse_of_code_in_research.qmd
cp ${DIR1}/reuse-of-data-in-research.md ${DIR2}/5_reproducibility/reuse_of_data_in_research.qmd
cp ${DIR1}/science-industry-collaboration.md ${DIR2}/4_economic_impact/science_industry_collaboration.qmd
cp ${DIR1}/science-literacy.md ${DIR2}/3_societal_impact/science_literacy.qmd
cp ${DIR1}/socially-relevant-products-and-processes.md ${DIR2}/4_economic_impact/socially_relevant_products_and_processes.qmd
cp ${DIR1}/societal-collaboration.md ${DIR2}/2_academic_impact/societal_collaboration.qmd
#cp ${DIR1}/table-of-contents.md
cp ${DIR1}/topic-trends.md ${DIR2}/2_academic_impact/topic_trends.qmd
cp ${DIR1}/transformative-publishing-agreements.md ${DIR2}/1_open_science/transformative_publishing_agreements.qmd
cp ${DIR1}/uptake-by-civil-society.md ${DIR2}/3_societal_impact/uptake_by_civil_society.qmd
cp ${DIR1}/uptake-by-patient-groups.md ${DIR2}/3_societal_impact/uptake_by_patient_groups.qmd
cp ${DIR1}/uptake-by-policy-makers.md ${DIR2}/3_societal_impact/uptake_by_policy_makers.qmd
#cp ${DIR1}/ ${DIR2}/3_societal_impact/uptake_by_the_artistic_sector.qmd
cp ${DIR1}/uptake-by-the-general-public.md ${DIR2}/3_societal_impact/uptake_by_the_general_public.qmd
cp ${DIR1}/uptake-in-citizen-science.md ${DIR2}/3_societal_impact/uptake_in_citizen_science.qmd
cp ${DIR1}/uptake-in-education.md ${DIR2}/3_societal_impact/uptake_in_education.qmd
#cp ${DIR1}/ ${DIR2}/3_societal_impact/uptake_in_medical_practice.qmd
cp ${DIR1}/uptake-in-the-legal-sector.md ${DIR2}/3_societal_impact/uptake_in_the_legal_sector.qmd
cp ${DIR1}/uptake-in-the-public-debate.md ${DIR2}/3_societal_impact/uptake_in_the_public_debate.qmd
cp ${DIR1}/uptake-of-research-result-by-industry.md ${DIR2}/4_economic_impact/uptake_of_research_result_by_industry.qmd
cp ${DIR1}/use-of-code-in-research.md ${DIR2}/2_academic_impact/use_of_code_in_research.qmd
cp ${DIR1}/use-of-data-in-research.md ${DIR2}/2_academic_impact/use_of_data_in_research.qmd
cp ${DIR1}/use-of-methods-in-research.md ${DIR2}/2_academic_impact/use_of_methods_in_research.qmd
cp ${DIR1}/use-of-patents-in-research.md ${DIR2}/2_academic_impact/use_of_patents_in_research.qmd
