# Effect on democracy {#indicator-name .unnumbered}
::: {}

## History
:::
## Description

\[Add text here\]

## Metrics

### #/% of references to research outputs in activist groups/NGOs reports/websites focussing on democracy

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### # research outputs addressing democracy

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### General indicator on democracy

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

## Known correlates

\[Add text here\]

## Notes

\[Add text here\]

## References

\[Add Zotero bibliography here\]
