---
author:
    - name: T. Venturini
      orcid: 0000-0003-0004-5308
      affiliations:
      - ref: cis-cnrs
      - ref: ugen

affiliations:
- id: cis-cnrs
  name: Centre national de la recherche scientifique
  department: Centre for Internet and Society
  city: Paris
  country: France
- id: ugen
  name: University of Geneva
  city: Geneva
  country: Switzerland 
---

# Uptake in and impact on to societal issues {#uptake-in-and-impact-on-to-societal-issues .unnumbered}

<div>

## History

| Version | Revision date | Revision     | Author       |
|---------|---------------|--------------|--------------|
| 1.0     | 2024-11-14    | First draft  | T. Venturini |
| 1.1     | 2024-11-26    | second draft | T. Venturini |
</div>

## Open Science Beyond Academia: An Exploration of Societal Uptake and Impact

Open Science is increasingly recognized as essential for advancing academic research and industrial innovation and a series of indicators have been developed in PathOS and elsewhere to assess the scientific and economic impacts of Open Science (covered in two sections of this handbook). Understanding the full impact of Open Science, however, requires looking beyond the boundaries of academia and industry to examine how OS resonates in other societal sectors generating broader but subtler outcomes. This section of the handbook considers how a variety of stakeholders engage with Open Science, the challenges in measuring its influence, and the different approaches being taken to assess its real-world effects.

Societal impacts are arguably the trickiest effects to assess, and in particular to attribute causally to Open Science. Decades of research in the social sciences have shown that direct causal explanations are often simplistic and sometimes dangerously misleading. This does not mean, to be sure, that causality cannot be investigated when examining social phenomena, yet it does mean that extra caution is necessary in order to draw conclusions that are respectful of the complexity of collective life.

There are at least three excellent points why measuring *societal impacts* is a complex endeavour:

- Society is, by definition, a sort of residual and all-inclusive category which encompasses all dynamics that cannot be fitted into more specific sectors. As a consequence, societal phenomena are extremely complex and always associated with a multiplicity of causes. The effect of open science therefore cannot be forcedly separated from the other influencing factors (i.e., pretending that OS alone is responsible for this or that societal trend) and should, on the contrary, always be investigated in combination with a multiplicity of other influences.

- Most societal changes take place over long periods of time and are rarely linear. What is observed in the short and medium term can and often is reversed or transformed in the long term when all sorts of unexpected consequences and secondary effects emerge.


- Different social groups hold varying perspectives on problems, their significance, and desired solutions. Improvement for some can be read as lack of real change by others or even deterioration. This is not just a normative question. Social groups disagree not only on how they evaluate a certain societal dynamic, but also on what dynamics are worth observing in the first place, how to define them, who should be included in the evaluation and so forth.

As discussed in the **Uptake and Impact on Societal Issues** chapter, assessing the impact of Open Science on societal issues necessitates a multi-step approach that involves:

1. Defining societal issues and its desired solution in ways that respect their ontological multiplicity and consider diverse perspectives and potential controversies surrounding them.

2. Monitoring issues evolution over short, medium and long-time, establishing robust and issue-specific qualitative and quantitative methods to track changes and ensure comparability across different time points.

3. Investigating the availability of Open Science resources related to the issue, evaluating the quantity and quality of these resources and comparing them to non-open resources.

4. Evaluating the mobilization of Open Science resources by actors engaged with the issue.

5. Disentangling the impact of Open Science from other factors through comparative analysis across different issues, time periods, and geographical or social spaces, along with qualitative exploration to understand causality paths.

This approach, obviously, cannot be resumed in a list of simple indicators and does not easily lend itself to a causality approach. These objective difficulties are recognized in the pages of the Handbook, which discuss questions related societal impacts but propose indicators that are oriented to assess societal *uptake*. Uptake research focuses on steps 3 and 4 of the approach described above and can be broadly defined as the extent to which different Open Science (OS from now on) resources (publications, data, software, etc.) are acknowledged and included by societal actors in their practices and discourses.

A final note of caution should be raised regarding the particular sectors and dimensions considered in the pages of this handbook. The range of social phenomena is extremely wide-ranging and encompasses hundreds, if not thousands of different issues studied across the social sciences (e.g. income/wealth inequality, segregation, urbanisation, demographics, gender, education, urban planning, media and public debate). Covering all these issues is not possible (for obvious reasons of space), but also not necessarily desirable. For some societal phenomena, it is very difficult to establish any influence of science at all (irrespective of it being open or not), and so we limited the scope of the handbook to focus on those areas where we have some hope of tracing connections back to science.

The specific ways for carrying out this tracing exercise are, of course, different in different societal sectors and the chapters of this section describes them:

**Uptake by Media** focuses on the visibility of OS in media, including traditional and social media platforms. The chapter acknowledges the limitations of simply tracking mentions, as these proxies of uptake do not reveal how the research is being used. It also explores alternative approaches, such as focusing on the mention of researchers or research topics, and different ways to track uptake, such as directly searching for journals or institutions.

**Uptake by Patient Groups**  investigates the utilization of OS outputs by patient advocacy groups. It emphasizes the role of these groups in bridging the gap between research and patient communities, improving quality of life through support, education, and advocacy. The chapter highlights the importance of analyzing the presence of OS resources in websites and reports as an indicator of OS integration into patient-focused discussions and resources.

**Uptake by Policy Makers**  examines the extent to which policy makers incorporate scientific publications into their decision-making processes. It introduces the concept of "policy citations," references to scientific publications in policy documents, as a key metric for assessing OS uptake in this realm. The chapter discusses platforms like Altmetric.com and Overton as valuable resources for tracking policy citations and their potential for developing derived indicators to gauge research impact on policy-making.

**Uptake in Education**  explores the integration of OS resources into educational materials, specifically focusing on educational handbooks and higher education syllabi. The chapter stresses the importance of understanding how OS is shaping educational content and methodologies to foster a culture of openness and collaboration in academia. It proposes analyzing the frequency of OS resource mentions as a metric for assessing OS uptake in education.

**Uptake in Medical Practice**  focuses on the integration of OS into medical practice, specifically examining its presence in medical guidelines and clinical trials. The chapter highlights the importance of understanding how scientific advancements and OS tools are translated into practical applications in healthcare. It suggests analyzing the proportion of medical guidelines and clinical trials that reference OS outputs as a key metric for assessing its real-world impact in the medical field.

**Uptake in the Legal Sector**  examines the impact of OS on the legal sector, encompassing legal knowledge, education, advocacy, policy-making, and professional activity. It defines "Legal OS" as encompassing Open Access publications in law, open educational resources in legal education, open legal databases and software, and open legal data. The chapter underscores the importance of understanding how OS influences and benefits various legal stakeholders, from law firms to government agencies, and emphasizes the justice and fairness argument for open access to legal knowledge.

Understanding the full societal impact of Open Science requires a multifaceted approach that examines its uptake and utilization across diverse sectors. This involves addressing methodological challenges in measuring impact, leveraging existing monitoring initiatives and developing tailored approaches for specific research objectives. By exploring Open Science's influence on scientific literacy, societal issue engagement, media coverage, and its integration into specific domains like healthcare, education, and law, we can gain a more comprehensive understanding of its role in shaping societal practices and knowledge dissemination.
