# Uptake in citizen science {#uptake-in-citizen-science .unnumbered}

History (please fill out in reverse chronological order, latest revision on top):

|         |               |                              |                           |
|---------|---------------|------------------------------|---------------------------|
| Version | Revision date | Revision                     | Author                    |
| 1.0     | 2023-02-07    | Finalised indicator template | T.P. Willemse, V.A. Traag |

## Description

\[Add text here\]

## Metrics

### #/% of non-experts mobilized/authoring in research outputs

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### #/% of "citizen science" projects per country/discipline/institutes/type of research

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### #/% of research outputs mentioned in "citizen science" projects

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### #/% of research outputs mentioned in Wikipedia

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### #/% of research outputs mentioned by skeptics websites

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### #/% of research outputs mentioned by fact-cheking websites

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

## Known correlates

\[Add text here\]

## Notes

\[Add text here\]

## References

\[Add Zotero bibliography here\]
