---
author:
    - name: M. Dulong de Rosnay
      orcid: 0000-0002-0297-7603
      affiliations:
      - ref: cis-cnrs

affiliations:
- id: cis-cnrs
  name: Centre national de la recherche scientifique
  department: Centre for Internet and Society
  city: Paris
  country: France
---

# Uptake in the legal sector {#uptake-in-the-legal-sector .unnumbered}

::: {.callout collapse="true"}


## History

| Version | Revision date | Revision             | Author                           |
|---------------|---------------|-----------------|---------------------------|
| 1.0     | 2024-03-29    | Second draft         | Melanie Dulong de Rosnay         |
| 0.6     | 2024-03-27    | Review               | Simon Apartis, Tommaso Venturini |
| 0.5     | 2024-03-26    | First draft          | Melanie Dulong de Rosnay         |
| 0.1     | 2024-02-23    | Preliminary research | Melanie Dulong de Rosnay         |

:::

## Description

This section presents two aspects of the indicator on the legal sector: the scope of legal open science (A), the context and the specificities of the legal sector (B).

**1. A. Scope and definitions of legal open science**

This indicator is meant to analyse the impact of open science in the legal sector and examine how its components (legal knowledge, legal education and life-long training, advocacy and policy-making, justice, legal innovation and legal professional activity) are influenced by and benefits from open science as opposed to closed access science.

Before doing so, it is necessary to capture the specificities of the legal sector and the nature of open science in the legal sector, and how it is relevant for, and produced by the legal sector. Following the OS definition, we are defining open access publications, open data, and open source code of the OS subfield of *Legal Open Science* as the sum of:

1.  Open Access scientific publications in the legal field (law journals, research in the field of juridical, jurisprudential and political sciences), related disciplines (public administration, sociology of law, political communication, law and economics, etc), and related interdisciplinary research (legal informatics, law and AI, etc),

2.  OER in the legal education (university, law school and professional training systems),

3.  Legal texts databases, legal platforms, legal tech, law and AI open source software, their metadata and interfaces, forming the open law movement,

4.  Legal open data, generated by research, and more broadly, public sector information, linked to the open data and open government movements.

Legal data is produced at several levels: local, regional, national, European, international, as well as public institutions (from cultural heritage to geographic data institutes), with each body both producing and reusing legal open science and open science in general. Public sector information includes a variety of outputs and formats, from administrative texts and public reports, to legislation and case law, but also datasets and public statistics (such as cadastre data, presence at the parliament, or cultural heritage information), and any data and information which is produced by public actors, or collected through public procurement, or made publicly available on public portals and platforms.

This forth category is hybrid, but considered as open science within the project since some legal data are produced by researchers working in the public sector, or by non-researchers following a scientific method, and since some are used as research data (primary source) to produce academic research.

We will consider primarily how Open Access publications, OER, Open Source software and open data produced by legal academics impact the legal sector, and secondarily how public sector information impact the legal sector.

Indeed, all actors: academic legal research, public sector (administration, legislator, justice, cities) and private sector (law firms, attorneys, in-house lawyers, non-profits, citizen association) produce legal Open Science, and further disseminate this knowledge to society, where those and other actors can benefit from Legal Open Science to fulfil their obligations or develop new activities. It is quite frequent for attorneys and practitioners to publish in legal journals or teach in law schools, judges participate to PhD examinations, civil servants and start-up computer scientists to publish at academic conferences.

**B. Context and specificities of the legal sector**

**Justifications** for opening up access to Legal Open Science including legal open data are twofold. In addition to the rational applicable to all open science to improve knowledge production and the tax-payer justification (tax-payers should be able to access to what their tax is funding), there is a justice and fairness argument: no one is supposed to ignore the law, citizens and moral persons to whom law and case law apply should be able to access these legal sources. Access to information or so-called sunshine legislations in the US were developed from the 1970s to fulfil that purpose.

Open science for the legal sectors will **benefit** a large range of stakeholders, from traditional law firms where lawyers work to defend and advise clients, to recent legal tech start-ups developing commercial services or law and AI based on legal open science, political parties and advocacy organisations developing their program, professional and citizen associations and non-profits working to preserve their or the public interest, primary and high school teachers creating educational resources, citizens who want to be informed, journalists and media who report on legal and governmental activity, etc.

A short **history** of the sector is necessary to understand how open applies to the legal sector. Originally, legal knowledge (scientific articles and case law) has been collected, organised and sold to law universities and law firms as structures and searchable databases by private publishers. The first *Legal Information Institutes* [@miller2005] offering case law were created between the 1990’s and the early 2000’s (CanLII, AustLII, FrLII), breaking the monopolies of private publishers of both law journals and case law.

The legal information industry shaped the availability of both legal texts and legal scholarship, especially in the Anglo-Saxon and Common Law world: oligopoly situation made it difficult to access before the development of public alternatives and open science repositories changed the market [@arewa; @janssens]. Legal texts and case law databases, before national portals offering open government data, started to structure primary legal sources (legal information in the form of law, regulation, administrative texts, and courts decision, offering an alternative to commercial platforms and market aggregators. In the early 2000, the 2003 PSI Directive revised in furthered legal access to public sector information (defined as public sector information, geographic data, cultural heritage, scientific publications and data). Together with the open data and open government movements, and the development of public sector information platforms such as Etalab or data.gov.nl, this Directive participated to removing legal obstacles to open data [@dulongderosnay2014]. Amended in 2019, the Directive focusing on open data and the re-use of public sector information has been instrumental in the development of legal open data.

## Metrics

### Number of legal articles deposit in Green OA repositories

A metric could be the proportion growth of the domain compared to other disciplines in HAL archive

### Number of legal journals in Gold or Diamond OA:

A metric could be the growth of the legal open science journals among all Open Edition journals during the last 20 years

These measures the growth of open legal research as a field as opposed to closed research, and the conformity of academics and researchers in law and related disciplines to OA mandates and recommendations of their universities and funders.

This indicator may not reflect very well some national markets, as close to 100% of European universities have a subscription to the main private databases and do not have problems to access to their own literature, unlike to researchers from non-law universities, governmental officers and private citizens who hugely benefit from OA publications.

### Number of legal open datasets made available on public portals

A metric could be the growth of the domain on data.gouv.fr or data.gov.nl.

The limit of this indicator is that it doesn’t measure reuse and impact.

### Number of citations of OA legal research and datasets in legal texts:

Both open and closed academic sources can be cited in justice opinions, parliamentary or governmental reports, and their influence in framing the policy or legal opinion might be deduced from the context.

#### Measurement

##### Existing datasources:

###### Open Access repositories

-   SSRN, the main venue for legal academics
-   institutional repositories
-   Arxiv, especially for IT law,
-   Scielo in Latinamerica
-   HAL in France

###### Open Acces journals

-   Open Edition journals: 22 in law
-   SciELO journals: 20 active journals with the query Derecho (law in Spanish)

###### Legal datasets on open data governmental portals

-   There are 35 149 datasets on data.gouv.fr, 23218 datasets on the Dutch portal data.
-   All similar open governmental national, regional and municipal platforms may be queried.
-   There are 50+ million items in Europeana, the European cultural heritage institutions platform
-   There are 19 legal datasets available on data.world: <https://data.world/datasets/legal>
-   There are 6 datasets responding to the query “ley” (law in Spanish) out of the 504 datasets on SciELO Data, the Dataverse-based Latinamerican Scientific Electronic Library Online: <https://data.scielo.org/dataverse/scielodata?q=&types=datasets&sort=dateSort&order=desc&page=1>

The limit of this indicator is that it doesn’t measure reuse and impact, only availability of legal datasets.

###### Datasources for citations

Both open and closed academic sources can be cited in justice opinions, parliamentary or governmental reports, and their influence in framing the policy or legal opinion can be deduced from the context.

The OpenAIRE Research Graph, as underlined in the Patients groups indicator, can be used to track which of the publications cited in legal texts are open access

Similarly to the indicator on the uptake by Policy-makers, which is very close to the legal sector, since they write the law, altmetrics tools can be used to analyse legal text such as Overton (<https://www.overton.io/>) indexing policy sources and how a scientific article has been mentioned in a policy document.

##### Existing methodologies

###### Cultural heritage information

Cultural heritage information, a subpart of public sector information and in that sense legal open science, must be made available for reuse under open terms and conditions since the 2013 Directive [@keller2014].

Its open access benefits to the society have already been measured by the European project inDICEs (Measuring the impact of DIgital CulturE), with analysis of the socio-economic impact.

Quantitative indicators can be number of visits of the Cultural Heritage Institutions websites, number of downloads of the artefacts, participation to activities based on reusing open cultural data.

More narrowly, open science metadata availability as open science data benefits research and education in art, art history, cultural studies and library information sciences and citations in those academic journals could be counted.

###### Value of open data ecosystems

For a more qualitative analysis of the value created by open data, the current European project ODECO (Towards a sustainable Open Data ECOsystem) is studying the value of open data ecosystems [@loenen2021], with several research interesting for PathOS: on the relation between open gov data and NGOs, on value creation in open data and its redistribution, on the co-creation of services between governments and companies. In particular, the methodology of the work-in-progress of ESR3 research could be an inspiration “To develop a framework for assessing the distribution of value of open data ecosystems, based on a detailed investigation of relevant literature and related practices, to measure value distribution in the open data ecosystem by applying the assessment framework to real cases in Belgium and Finland (comparative case study approach), to investigate models and approaches for redistributing value across different stakeholders in open data ecosystems (on value creation in garden data ecosystems [@cazacu2023].

###### Qualitative assessment of the impact of legal open science beyond citations

There are many limits to a quantitative citation approach.

Many law journals are not indexed with DOIs, which will make automated queries impossible.

National legal texts and scholarship databases will not be in English but in national languages.

If some lawyers will have to cite the source for their reasoning in some instances in similar ways than academic citations, in other cases, some may also use OS publications for self-training purposes, to learn about a new topic. For example, IT lawyers will need to understand how AI works because defending their clients’ cases on the topic. In that case, there will be no citation in an output document.

Also, some outputs are private counselling notes delivered to clients, which are not publicly available and impossible to query, but may be instrumental in companies decisions with a measurable impact in economic growth, market share, employment, and tax return, if for instance, the decision is to start a new service (such as a legal audit by a start-up before launching a AI product). Another output would be professional training, and the development based on OS of either OER or closed access training material to educate lawyers to a new topic, such as smart contract.

Under these circumstances, a qualitative methodology could be useful, with interviews of selected representative attorneys, legal assistants, judges, law clerks, legal tech from founders to interns, public sector and administration officers in selected countries and cities. Questionnaires could help better understand if and how OS is read and the actual impact it may have compared to closed science behind paywalls.

Finally, it is crucial to include in any qualitative study or questionnaire a sample of countries of the Global South, where lawyers do not have access to major commercial databases of legal sources (law, case law, academic articles) such as Westlaw, because of prohibitive costs. This is why OS is so important, not only because of its measurable impact on Global South students and academics, but also for professionals.

Once these limitations and pointers to qualitative assessment have been acknowledged, it is nevertheless possible to perform the same automatic queries than for other indicators, for instance the patient groups community or the policy-makers, in order to provide a possibly limited, top of the iceberg understanding of the reuse of OS by the legal sector, without evidencing all the real impact.

## Known correlates

In the absence of citation, it is difficult to assert that a legal decision has been taken following a research result published in an Open Access journal possibly relying on an Open Data set. Correlation (or coincidence, as explained in the Societal Issues indicator) cannot be interpreted as causation, or direct and only impact.

## Notes

A systematic literature review on the topic on the impact of open science in the legal sector seems difficult to perform , because keywords lead to references addressing different research questions, such as the legal aspects of open science.