---
author:
    - name: E. Delugas
      orcid: 0009-0000-4638-1062
      affiliations:
      - ref: csil
    - name: G. Consiglio
      orcid:
      affiliations:
      - ref: csil
    - name: G. Catalano
      orcid: 0000-0002-3638-1904
      affiliations:
      - ref: csil

affiliations:
- id: csil
  name: Centre for Industrial Studies
  city: Milan
  country: Italy
- id: tgb
  name: Technopolis Group
  city: Brussels
  country: Belgium

title: Innovation output
---

::: {.callout collapse="true"}
# History

| Version | Revision date | Revision | Author |
|------------------|------------------|------------------|-------------------|
| 1.4 | 2025-03-07 | Third draft | Delugas E., Catalano G., Caputo A. (reviewer) |
| 1.3 | 2024-04-26 | Second draft | Delugas E., Consiglio G., Catalano G. |
| 1.2 | 2024-04-25 | Peer review | V.A. Traag |
| 1.1 | 2024-03-27 | First draft | Delugas E., Consiglio G., Catalano G. |
:::

# Description {#description .unnumbered}

The innovation process can be defined as the transformation of ideas into valuable outputs, such as new products, services, or processes. It consists of a series of stages in which inputs are converted into intermediate outputs, which are subsequently refined to generate an innovation [@janger2017]. These inputs often include research findings, investments in R&D, creative ideas, and human resource capabilities. Intermediate outputs may be tangible or intangible results generated during the innovation process, including patent families[^patent-family], prototypes, conceptual designs, process improvements, or validated business models. According to the Oslo Manual [@oecd_oslo_2005], innovation represents a step beyond intermediate outputs, referring to a new or significantly improved product or process (or a combination of both) that substantially differs from a unit’s previous offerings. Innovations can range from incremental improvements to disruptive changes that reshape markets or societal practices. For a product to be considered an innovation, it must be made available to users, while a process innovation must be implemented within the organisation.

[^patent-family]: A patent family differs from a patent application by offering a broader view of innovation. A patent application is a formal request for legal protection, including technical details, claims, and drawings, initiating an examination process to assess novelty and utility. In contrast, a patent DOCDB family groups related patent’s applications across countries based on a shared priority application, enabling global tracking of an invention's variations.

Open Science (OS) resources serve as inputs in the innovation process, contributing to productivity and economic growth. While empirical studies remain limited, open practices are suggested to enhance early-stage research by improving efficiency, reducing access costs, and enabling broader exploration[^os-economic-impact]. More substantial evidence supports the role of open/FAIR data in fostering multidisciplinary collaboration, accelerating product development, and facilitating technology deployment, though it requires adjustments in business models and policies [@williams2013;@arshad2016;@giovani2017;@nielsen2023]. Open access to scientific journals increases accessibility to academic research, leading to higher patent citations and greater integration into technological advancements, particularly in biomedicine and technology sectors, though its impact remains difficult to measure [@bryan2021;@jahn2022]. Similarly, open-source software fosters innovation by enabling collaboration, reducing development barriers, and setting de facto standards, benefiting start-ups and emerging technologies like AI and blockchain, despite challenges in balancing openness with intellectual property concerns [@conti2021;@EC_impact_2021].

[^os-economic-impact]: See for further details on the literature on OS economic impact [@tsipouri2025].

Emerging literature suggests that OS resources may play varying roles in the innovation process. In some cases, they are critical to the development of intermediate outputs and innovations. For example, open protein data are essential for drug development, significantly accelerating or even enabling the discovery process. In other cases, their contribution is more nuanced, such as facilitating companies’ access to research papers, which increases exposure to new ideas that may eventually lead to innovations in the production process.

The proposed indicator “Innovation Output” aims to measure the extent to which the OS contributes to the outputs of the innovation process, encompassing both intermediate outputs and innovations[^innovation-output]. Building on previous studies accurately discussed by @dziallas_innovation_2019, it envisages metrics that capture impacts at the organisational and ecosystem levels. Similarly, they can be understood as metrics capturing innovation at different stages of the innovation process, the development and outcome phases[^research-phase]. In some cases, these metrics may also apply to broader analytical units, such as geographical regions, specific industry sectors, or projects influencing multiple beneficiaries. While not exhaustive, the following metrics are suggested to assess the impact of OS on innovation outputs[^earlier-adoptions]:

[^innovation-output]: With this labelling, we do not claim that patents or patent families, for instance, are all innovation outputs in the sense of the Oslo Manual [@oecd_oslo_2005], but rather that they are outputs resulting from the use of different innovation inputs, including OS.

[^research-phase]: Other metrics can be identified at the initial “research phase” of innovation process, but they are left to the academic sphere.

[^earlier-adoptions]: These metrics build on indicators adopted in different contexts. For instance, the Open Science Monitor mentioned that new products, services and technologies has been used in the [White Rabbit Project](https://white-rabbit.web.cern.ch/) of CERN to measure how companies were able to reuse and sell White Rabbit switches and nodes, along with their services, to different organisations in multiple industrial settings. Similarly, @florio_big_2018 have used similar metrics to measure innovation triggered by CERN in its supplier firms. Also, they have been indicated as monitoring indicators in the [RIPATHS](https://ri-paths-tool.eu/en) framework.

1.  Number and % of new technologies developed using OS resources (organisation level)
2.  Number and % of start-ups/spin-offs founded based on OS technologies (ecosystem level)
3.  Number and % of patents filed using OS resources (organisation and ecosystem levels)
4.  Number, %, and value of new products or services developed using OS resources (organisation level)
5.  Average increase in companies’ patent portfolio value thanks to patent filed using OS resources (organisation level)

Assessing the impact of OS on innovation outputs in industry presents several challenges, primarily due to limited empirical evidence and the difficulty of distinguishing between open and closed knowledge sources. Key challenges include:

-   *The lack of systematic data sources*: A major obstacle is the absence of comprehensive, systematic data sources that capture the extent to which innovation relies on OS versus proprietary knowledge. Without reliable quantitative metrics, assessing OS’s role in driving innovation remains imprecise. For instance, OS adoption may enhance organisational culture by fostering innovative business models, improving business strategies, opening new markets, or contributing to new ideas within an organisation. Measuring these impacts requires the design of ad-hoc surveys - although costly and time-consuming - as automation is not yet a viable option for data collection[^innovation-measurement].

[^innovation-measurement]: @dziallas_innovation_2019 provide a comprehensive list of references on indicators, factors, methods, and other details related to innovation measurement throughout the innovation process not in the context of OS.

-   *Time lag between OS use and innovation outcomes*. Another challenge stems from the inherent time lag between the use of OS inputs and the eventual materialisation of innovation. Developing novel products or technologies often takes years, making observing short-term impacts difficult. Early indicators may be subtle or difficult to detect, increasing the risk of underestimating OS’s contributions simply because it is too early to measure them. Without longitudinal studies, tracking OS’s influence over time becomes even more complex.
-   *Measuring the Causal Impact of OS on Innovation*. Determining whether OS directly drives innovation remains a fundamental challenge. Even with extensive quantitative indicators, establishing causality is difficult. If all scientific knowledge were open, isolating OS’s effect on innovation from other contributing factors would be impossible. As discussed in the [causality introduction](../0_causality/causal_intro/article/intro-causality.qmd), rigorous research designs are required, specifically for economic impacts in [cost savings](../0_causality/open_data_cost_savings.qmd). One approach involves comparing the innovation performance of similar organisations using identical research inputs, with the only difference being whether the source is open or proprietary. However, just as data collection cannot be fully automated, assessing causal impact requires a complex research framework. For these reasons, none of the metrics proposed below claim any causal impact determined by OS.
-   *Selecting the appropriate metrics.* Selecting the right metrics to measure innovation is another challenge. Identifying new products, processes, or technologies is neither straightforward nor entirely objective. For clarity, we refer to the definitions outlined in the Oslo Manual [@oecd_oslo_2005]. While patent families are a widely used proxy for innovation [e.g., @wuchty2007;@schoenmakers2010], they do not always translate into actual commercialised innovations. However, to introduce simple indicators to track OS’s impact across different organisations, patents serve as a reasonable proxy for several reasons. Patent data are systematically collected and widely available, facilitating a degree of automation in impact assessment. They provide objective, long-term insights while mitigating biases associated with survey-based research, such as self-selection, over-optimism, and subjectivity [@castelnovo2023]. Patent citation analysis can distinguish whether references were initially used by the inventor or introduced during the evaluation process, helping to assess the influence of OS on technological advancement. Moreover, patent databases can support rigorous research designs, potentially enabling causal assessments. For example, linking patent citations to the scientific sources they reference could help determine whether an innovation is disruptive or incremental. Some databases even classify citations by novelty level. A more advanced measure proposed by [@funk2017] applies network analysis to assess whether a patent consolidates or disrupts existing technology landscapes. Nonetheless, patents alone cannot fully capture OS’s impact. Surveys could provide deeper insights into how OS is integrated into innovation processes, its interaction with proprietary research, and the extent to which organisations leverage OS without relying on patents.

# Metrics {#metrics .unnumbered}

## \# / % of new technologies developed using OS resources

The metric “new technologies developed using OS resources”- expressed as an absolute number or percentage over the total technologies developed by the organisations under analysis - can be measured through surveys. However, without being embedded within a rigorous research design, such surveys alone cannot establish a causal relationship between OS resources and innovation outcomes.

## \# / % of new start-ups and spin-offs founded based on OS technologies

The metric “new start-ups and spin-offs founded based on OS technologies” - expressed as an absolute number or percentage of total start-ups or spin-offs within a given ecosystem (e.g., industry or region) - can be measured through surveys to assess the significance of OS in the start-up’s business model. Alternative data sources such as crowdfunding platforms (e.g., Kickstarter) and start-up databases (e.g., Crunchbase, PitchBook, Dealroom) can also provide valuable insights.

## \# / % of patent families filed citing OS resources

The metric “number and percentage of patent families filed citing OS resources” evaluates the contribution of OS to legally recognised innovations. By highlighting the role of OS in developing proprietary technologies and intellectual property, this measure provides insights into how openly available knowledge supports innovation. This metric can be measured through surveys, patent and citation analysis, or a combination of both. Whenever the OS resource under analysis does not have a detailed reference (e.g., open data), the citation analysis might be implemented by means of “mention analysis”. A concrete example is provided in the UniProt case study.

Going beyond a simple count of the legally recognised innovations and analysing the actor responsible for the citation, this metric can help assess the degree of novelty that OS resources contribute to a given patent family. When measuring impacts at the organisational level, it is crucial to focus on citations included in the patent text by the inventor rather than those introduced during the patent examination process, as the former more accurately reflects the direct usage and influence of OS on innovation.

## Average increase in companies’ patent portfolio value thanks to patents filed using OS resources

This metric aims to quantify the monetary gains linked to the patents filed due to the uptake of OS research findings. In particular, this is done by measuring the average increase in companies’ patent portfolio value thanks to patents filed using OS resources. This approach provides a monetary estimation of industry adoption of OS research, making it a practical and easily interpretable indicator for industry stakeholders compared to broader metrics that simply count patent families.

However, this metric alone does not fully capture the total value generated by OS resources. To enhance its explanatory power, it should be complemented by patent citation analysis, at a minimum, to determine the proportion of OS-derived citations within the total references in a patent. Furthermore, as previously noted, qualitative insights are essential to assess the relative importance of OS resources compared to other scientific inputs. Only through in-depth qualitative analysis can the true impact of OS on innovation be accurately determined.

## \#, %, and value of new products or services developed using OS resources

The metric “new products and services developed using OS resources” measures the influence of OS research outputs on developing organisational innovations. It can be expressed in three ways:

-   Absolute number of new products and services developed using OS resources.
-   Percentage of total products and services based on OS.
-   Monetary value, represented by the share of profits generated from these OS-driven innovations.

By capturing both quantitative and financial dimensions, this metric provides a comprehensive view of how OS contributes to product and service innovation within organisations. It helps assess the tangible impact of OS research on market offerings and economic performance.

# Measurement {#measurement .unnumbered}

Two complementary approaches can be used to measure this indicators: surveys and patent and citation analyses.

1.  Surveys offer a robust approach to evaluating the proposed metrics for this indicator while providing a comprehensive understanding of OS’s role in the innovation process. They can be conducted within a single organisation or across a representative sample of organisations and sectors that have likely used OS inputs in developing new products, services, technologies, and proprietary innovations. In particular, surveys are valuable for capturing data on new start-ups and spin-offs. Surveys help determine the extent to which OS research outputs have facilitated innovation over a given period by collecting quantitative data on the total number of innovations within specific entities or sectors. Additionally, they provide qualitative insights into the use of OS resources, including details about the organisations involved, the types of OS research resources used, and whether they are combined with closed research outputs.
2.  Patent and citation analyses are valuable for measuring metrics such as “patent families filed by the industry citing OS resources” and “increase in companies’ patent portfolio value thanks to patent filed using OS resources”. This approach relies on structured online databases that collect and organise patent documents, including The Lens, PATSTAT, and Orbis IP. The choice of the database depends on the specific information required. For instance, Orbis IP enables the linkage between patents’ applicants and their financial data, especially when the applicant is a company, , offering a more comprehensive analysis of corporate economic growth. These data sources facilitate advanced searches, returning a list of patents and key details such as titles, abstracts, citations, and international patent classification codes, backward and forward citations, and so on. The extracted data can then be filtered, downloaded, and analysed to quantify OS-related patents. However, patent analysis has limitations. One key challenge is the possibility of incorrect or missing citations – or mentions – of OS resources. If an innovation relies on OS inputs, but the corresponding patent fails to cite or mention them—or is doing it inaccurately—it becomes difficult to establish a direct connection. Patent databases are not always complete, and patent metadata provided may vary between sources. While patent analysis allows for automated quantification of OS’s impact, it does not capture the qualitative significance of OS contributions compared to other innovation factors. In other words, relying solely on patent data may overlook the extent to which OS resources were critical to developing a given patent. Similarly, citation or mention inaccuracies could lead to underestimating OS’s role in innovation. To address these limitations, surveys can complement patent analysis by providing qualitative insights into how OS inputs are integrated into the patenting process. Unlike automated analysis, surveys enable a deeper exploration of the extent to which OS resources contributed to a patent. While surveys require manual data collection and cannot be automated, they offer a richer understanding of OS’s impact.

A combined approach—leveraging both patent analysis and surveys—is recommended to comprehensively assess OS's role in innovation. This dual methodology ensures quantifiable measurement and a nuanced interpretation of OS’s influence on technological and economic advancements.

## Existing methodologies

### Survey

An effective survey questionnaire should include a structured set of questions designed to collect both quantitative and qualitative data on the role of OS in innovation. The questionnaire should aim to assess how OS resources contribute to business models, start-up survival, product and service development, and patent filings. Examples of key question types include:

Assessing OS’s Impact on Business and Start-ups

-   Can you explain in detail the importance of using OS resources for your business model?
-   Do OS resources contribute to the probability of survival of your start-up?
-   Without OS resources, do you believe the start-up would have been founded anyway?
-   What aspects of your business would have been different without OS resources?

Measuring Innovation Outputs

-   How many new products and/or services has your organisation developed in the last year?
-   How many of these products and/or services were developed using OS resources?
-   How many technologies has your organisation developed in the last year?
-   How many of these technologies were developed using OS resources?
-   Can you provide an estimate of the monetary value of these innovations?

Assessing OS’s Role in Patent Development

-   How many new patent applications (i.e., earliest filing) has the organisation filed during the last year?
-   How many of those new patent applications were developed using OS resources?
-   To what extent the OS resources use have been crucial to develop those new patent applications?
-   Which value added have the OS resources used provided you with?
-   Can you provide an estimate of these patents' economic and monetary value?

To better understand the extent to which OS resources contribute to product and service development, additional questions can be included to identify the types of OS resources used and their integration with closed research outputs. This requires investigating the OS practices adopted by organisations and how different research outputs are combined. Examples of relevant questions include:

-   What types of OS resources (e.g., software, libraries, tools) does your organisation commonly use to develop products/services/technologies?
-   What is the average share of OS resources/of closed research used in patents developed in the last year?
-   How are OS resources blended with proprietary or closed research outputs in your development process?
-   Does your organisation prioritise open or closed research outputs in its innovation processes?
-   How has the adoption of OS resources impacted the innovative capabilities of your organisation?

While surveys can provide valuable insights, several challenges must be considered. In the first place, there is a risk of *overestimating or underestimating* the role of OS input if not all research inputs contributing to the innovation outputs are thoroughly investigated. This can also be related to the *temporal dimension*. Assessing the actual impact of OS on innovation output development in a single survey may be difficult, as the materialisation of impact may not be immediate, and follow-ups might be necessary.

Other issues might be related to the *technical design* of the survey and its representativeness. When the metric aims to measure contributions across multiple organisations, particularly for getting a metric representative of an entire industry (e.g., pharmaceutical sector) or a geographical area (e.g., a region), ensuring a representative sample can be challenging. Further, *self-selection and other subjective biases* might affect the representativeness of the analysis. Different types of organisations, such as for-profit and non-profit entities, may vary in their willingness to disclose OS usage data.. Private companies, particularly those linking patents to innovation output, may be reluctant to reveal their reliance on OS resources. Additionally, profit-oriented organisations may avoid publicly acknowledging OS contributions to avoid potential customer concerns about product pricing.

Addressing these challenges requires careful survey design, ensuring a balanced sample, and considering follow-up methodologies to track OS’s long-term impact on innovation.

### Patent and Citation Analyses

This methodology allows tracking a given OS resource impact on legally recognised inventions. As mentioned above, two different analyses can be performed.

Examples of these applications can be found in evaluating Alba [@catalano2021], two synchrotron light facilities employed for scientific research. These research infrastructures support research in multiple fields, including physics, chemistry, biology, health, and environmental sciences. Further, it has been employed in the UniProt case study, using a “mention analysis” approach to account for the fact that UniProt data are not cited in the conventional manner of academic papers.

The methodology primarily involves the use of Lens and Orbis IP. Please refer to the indicator on [science-industry collaboration](science_industry_collaboration.qmd) for an application of patent/citation analysis using PATSTAT. The analysis can be conducted at the level of individual patent applications or patent families. However, focusing on patent families is generally preferred, as it establishes a more precise linkage between OS resources and inventions and avoid double-counting, thereby enhancing the assessment of their contribution to innovation. Although it must be tailored to the specific characteristics of the OS practices under assessment, three main steps can be identified.

1.  Definition of the search strategy
2.  Conducting the Patent Search and Data Retrieval.
3.  Analysis of patents’ data.

*(1) Definition of the search strategy*

The first step consists of defining the search strategy for the analysis. This may follow two complementary approaches:

1.  Publication-Based patent search: this method focuses on identifying patents that have been generated from scientific papers that either open access or result from the use of an OS resource. To implement this approach, it is necessary to compile, as a first step, a detailed list of relevant publications, which can be obtained through Open Science resource managers (e.g., institutional repositories, research infrastructure databases) or searching in Open-access databases (e.g., OpenAIRE, which aggregates scientific publications). Once the publication list is established, patent databases can be searched for patents that cite these papers, thereby providing insights into the direct and indirect influence of OS on patented innovations.
2.  Keyword-Based patent search: this approach involves identifying and defining a set of keywords associated with the OS resource under evaluation. These keywords should be unambiguously linked to the resource, such as the name of the OS practice or tool (e.g., a software package, database, methodology) and technical terms or concepts that are directly tied to the OS resource. The identified keywords are then used to search patent databases to assess their presence in patent documents (e.g., in titles, abstracts, claims, or citations). The search strategy can combine these two approaches. This enables the capture of both direct and indirect influences of OS resources on patent development, ensuring a more comprehensive understanding of their role in technological advancements.

*(2) Conducting the Patent Search and Data Retrieval*

Once the search strategy has been defined (see Step 1), the next step involves executing the search and retrieving patent data that cites and/or mentions the selected publications and/or keywords. This process requires accessing specialised patent databases, which vary in scope and functionality. The choice of the database depends on the type of input (publications and/or keywords) identified in the previous step. The most relevant databases include:

-   The Lens (via PatCite) is best suited for publication-based searches (i.e., identifying patents citing specific scientific papers and keyword searches). It allows users to filter results by factors such as sector of application or type of patent owner (e.g., firms, universities, public institutions). Moreover, it also incorporates data analysis tools on the online platform.
-   Orbis IP provides a comprehensive linkage between patent data and company financial information. It is ideal when analysing patent ownership characteristics, as it integrates patent records with financial and corporate data.
-   PATSTAT (EPO Worldwide Patent Statistical Database) is a valuable source for conducting large-scale statistical analysis on patent trends. It enables advanced querying of patent families, citations, and classification codes.
-   EUIPO (European Union Intellectual Property Office) helps retrieve patents related to trademarks and intellectual property rights registered within the EU.

A more detailed description of these sources is provided in Section 4 below. For keyword-based patent searches, most data sources allow searches across various sections of a patent (e.g., title, abstract, main text, claims, citations). Searches can be performed across multiple databases to maximise coverage, and results can be combined to form a comprehensive dataset. The Lens (PatCite) is particularly useful for publication-based patent search, as it enables direct retrieval of all patents that cite a given scientific publication. Results can be further filtered and refined based on patent classification codes (to focus on specific technology sectors), geographical origin (to analyse patents filed in specific countries or regions), and type of applicant (e.g., distinguishing between corporate, academic, and public sector patents).). All the data sources allow for the export of search results in structured dataset formats (e.g., CSV, Excel, JsonL, SQL databases). These datasets typically contain key patent details, including the publication number, the country of the applicant, the owner, the patent classification code, the year of publication, the value of the patent (only Orbis IP), patent family, authors/inventors, citations (both patent and non-patent references) and the origin of the citation (whether cited by the inventor or by examiners) (only in PatStat and Lens), degree of novelty associated with the citation (only PatStat), etc.

By systematically searching, retrieving, and organising patent data, this step ensures a robust foundation for subsequent analysis, providing valuable insights into the role of OS resources in technological innovation.

*(3) Analysis of patents’ data*

After retrieving and compiling the relevant patent datasets (see Step 2 above), the next phase involves conducting a detailed analysis tailored to the specific objectives of the assessment. This step provides quantitative and qualitative insights into the role of OS resources in driving technological innovation and patent activity. The analysis can be structured along several key dimensions:

-   Overall citation metrics. This includes the total number of patents citing OS resources, categorised into total citations (all references to OS resources in patents) and inventor citations (explicit references made by the patent inventor). It also involves comparing OS citations with closed-source citations to evaluate the relative importance of OS inputs.
-   Patent novelty and knowledge diffusion. This examines the level of novelty associated with OS citations compared to closed-source references. It includes identifying whether OS-cited patents contribute more to breakthrough innovations (e.g., through forward citation analysis), incremental improvements, or high-impact innovations.
-   Temporal trends in patent publications. This involves tracking the evolution of OS-citing patents over time to detect adoption patterns and their impact on innovation. It includes analysing the growth rates of OS-related patents compared to general patent trends and assessing whether notable increases in activity follow major OS advancements or policy changes.
-   Sectoral analysis. By leveraging patent classification codes (e.g., IPC, CPC), this aspect identifies the key industries where OS-cited patents are most prevalent. It assesses whether specific sectors, such as pharmaceuticals, biotechnology, or artificial intelligence, rely more heavily on OS inputs and identifies emerging fields where OS resources are more significant in accelerating innovation.
-   Comparative analysis within specific sectors. Within a defined industry and timeframe, this involves comparing the number of patents citing OS resources against the total patents published in that sector. It also examines the proportion of OS-influenced patents as a percentage of overall industry patents.

# Data Sources for Patent Analysis

## The Lens

[The Lens](https://www.lens.org/) is a comprehensive platform that provides a broad array of information and analytics on patents (more than 150 million), scholarly research, and policy documents. It offers tools to explore the connections between patents and scientific literature, enabling users to understand the impact of research and the global patent landscape. The Lens offers completely free access for private individuals and non-profit personal and institutional accounts.

Through its application, “Patent”, it allows users to search within the patent database. The searches can be restricted to specific sections of the patents (e.g., title, main text, citations, etc.), and the results can be filtered by various elements (e.g., jurisdiction, document type, etc.). A very useful feature of “Patent” is that it enables the download of results in a structured Excel format so that they can be further analysed. Note that the full text of the patent is not always available, namely for less than 29 million patents. This limitation can affect the results of searches by keywords.

As an example, to obtain the widest result possible, a keyword known to be unequivocally related to the OS resource under evaluation can be searched by filtering the “Field” section with “All Fields”. The result will be a list of all the patents that include the keyword in one of their sections. This list can then be downloaded and further analysed, for example, by filtering the patents referring to a specific jurisdiction. The results can also be filtered by “Classification” and, in particular, by the CPC Classification code, a patent classification system based on the patents’ scientific or economic application sector. Filtering by the CPC Classification code allows for comparing the results with the total number of patents referred to the corresponding code. Finally, another application of The Lens, “PatCite”, also allows for searching for patents citing a scientific paper from a given list.

## Orbis IP

Orbis IP is a private database that merges company and patent information. Its interface enables searches within a collection of approximately 110 million patent documents. Similar to The Lens, it allows for keyword searches in specific patent fields. Various variables can also filter the results (e.g., jurisdiction, document type, etc.). Furthermore, the results obtained through Orbis IP can be downloaded in a structured Excel file for further local analysis. Unlike The Lens, all the patents available in Orbis IP include the full text, broadening the potential results obtainable through a keyword search. Also, Orbis IP is the only one that includes the monetary value of the patent.

As an example, to achieve the broadest result possible, a keyword known to be unequivocally related to the OS instrument can be searched by selecting “Patents” in the main search bar or using the “Patent text” tool. This will search the given word across all possible sections of the patent. The result will be a list of all the patents that include the keyword in one of their sections. This list can then be downloaded and further analysed. In this case, the patents can be filtered by the CPC Classification code, allowing for comparing patents relating to a specific domain with the total number of patents classified in that domain. Unlike other data sources, Orbis IP does not allow for searches based on the scientific publication mentioned in the patents. This means that it is not possible to use papers known to have used OS inputs as inputs for patent searches through this database. Finally, it is important to note that access to this data source requires the purchase of a license.

## Patstat

[PATSTAT](https://inspire.wipo.int/patstat-online) is a commercial product offered by the European Patent Office (EPO) and is a comprehensive database that contains bibliographical and legal status patent data. PATSTAT allows users to perform sophisticated statistical analysis of patents, facilitating a deeper understanding of patenting trends, technology developments, and the competitive landscape in various fields. The database is available in different formats for offline analysis or can be consulted online, making it a versatile tool for users with varying needs.

## EUIPO

The European Union Intellectual Property Office ([EUIPO](https://www.euipo.europa.eu/en)) is the agency responsible for managing the EU trade mark and the registered Community design. The EUIPO website provides comprehensive resources, including databases for EU trade marks and registered designs, information on intellectual property law and practice, and access to online applications and management systems for EU trade marks and designs. Additionally, the site offers learning resources, news, and updates on IP matters relevant to the European Union.

## Kikstarter, Cruchbase, Pitchbook, and Dealroom

Kickstarter is a crowdfunding platform that enables entrepreneurs, artists, and creators to raise funds for their projects through public contributions. It primarily supports creative ventures, including technology, design, film, music, and gaming. Unlike traditional investment platforms, Kickstarter operates on an all-or-nothing funding model, meaning projects only receive funds if they reach their funding goal. It provides insights into early-stage innovation trends, emerging products, and consumer interest in novel ideas.

Crunchbase is a business intelligence platform that provides comprehensive data on start-ups, investors, funding rounds, acquisitions, and industry trends. It is widely used by investors, analysts, and entrepreneurs to track company growth, funding history, and market positioning. Crunchbase aggregates data from various sources, including press releases, self-reported company information, and automated tracking of investment activities. It is particularly useful for identifying trends in venture capital, mapping start-up ecosystems, and analysing funding patterns across industries.

PitchBook is a financial data and research platform that offers in-depth information on private and public market investments, including venture capital (VC), private equity (PE), and mergers & acquisitions (M&A). It provides detailed financial metrics, investor portfolios, and deal histories, making it a key resource for finance, investment, and corporate strategy professionals. Compared to Crunchbase, PitchBook offers more granular financial data, including valuations, deal multiples, and revenue estimates, often sourced from regulatory filings and proprietary research.

Dealroom is a business intelligence platform that provides data and insights on start-ups, venture capital, private equity, and innovation ecosystems. It is widely used by investors, corporations, and policymakers to track emerging companies, funding trends, and market developments. Dealroom aggregates data from public sources, proprietary research, and partnerships with governments and industry organizations, offering a comprehensive view of the European and global start-up landscape. Compared to Crunchbase and PitchBook, Dealroom places a strong emphasis on mapping start-up ecosystems, providing network intelligence, and analysing sector-specific innovation trends, making it a valuable tool for understanding high-growth industries and investment opportunities.

# Operationalization in Case Studies

## PathOS Case Studies

This indicator has been operationalized in the following case studies:
- ELIXIR´s Bioinformatics Resources

Further details are available in Deliverable D3.3 of PathOS, accessible through the [PathOS Zenodo community](https://zenodo.org/communities/pathos/records?q=&l=list&p=1&s=10&sort=newest).

# Known correlates {#known-correlates .unnumbered}

In addition to this general indicator measuring the impact of OS on innovation, two other indicators examine specific aspects of OS’s role in the innovation process: [science-industry collaboration](science_industry_collaboration.qmd) and [socially relevant products and processes](socially_relevant_products_and_processes.qmd). The impact of OS on innovation within the academic sphere, such as its effects on publications and citations, is covered in the [academic impact section](../2_academic_impact/introduction_academic_impact.qmd). Likewise, the cost savings generated by OS—through reduced time and increased R&D efficiency as discussed in the [CBA methodological note](https://zenodo.org/records/10277642) [@delugas2023a] —are addressed in the [cost savings](cost_savings.qmd) indicator, while its contribution to the economic value of innovation is discussed in the [economic growth](economic_growth_of_companies.qmd) indicator.

# Notes {#notes .unnumbered}

The authors are grateful to Bastian Rake, Katharina Lauer, and Angelo Romasanta for their fruitful comments and suggestions.
