---
author:
    - name: E. Delugas
      orcid: 0009-0000-4638-1062
      affiliations:
      - ref: csil

affiliations:
- id: csil
  name: Centre for Industrial Studies
  city: Milan
  country: Italy

title: Introduction to Economic Impact


repo-actions: true
---

::: {.callout collapse="true"}
# History

|         |               |               |            |
|---------|---------------|---------------|------------|
| Version | Revision date | Revision      | Author     |
| 1.1     | 2024-12-09    | Revision      | E. Delugas |
| 1.0     | 2024-12-06    | First version | E. Delugas |
:::

Open Science is transforming the research landscape by promoting increased transparency, fostering collaboration, and driving innovation. It has become a fundamental element of policy frameworks worldwide. However, while its role as a catalyst for progress is widely acknowledged, empirical evidence on the economic impacts of OS remains scarce. One significant challenge in generating such evidence lies in the difficulty of collecting meaningful information on the use of OS among diverse stakeholders.

This section of the handbook aims to address this gap by providing guidance on collecting relevant data to effectively capture the realisation of economic impacts. Specifically, it explores the potential economic impacts generated by OS over different time horizons, recognising that these impacts are strongly interlinked, occur simultaneously or sequentially, and may even materialise in the very long term. It is important to emphasise that our goal is to capture the contribution of OS in enhancing the proposed metrics, without making any claims of causality in what is measured by each of them. As discussed in the [introduction on causality](../0_causality/causal_intro/article/intro-causality.qmd), achieving such causality would require fulfilling many additional conditions.

Some of the proposed indicators, particularly cost savings and, to some extent, innovation output and science-industry collaboration, are better documented in the existing literature and can be more easily implemented by private or public organisations to monitor OS uptake and its immediate effects. Conversely, other indicators are inherently more complex and deeply intertwined with empirical research. These require more nuanced analysis to disentangle the specific impacts of OS from other contributing factors, thus highlighting the need for dedicated research efforts to reliably identify and measure the broader effects of OS.

|  |  |  |  |
|------------------|------------------|------------------|------------------|
| **Indicator Name** | **Time Horizon** | **Description** | **Level of Development** |
| Cost Savings | Short-term | This indicator focuses on the efficiency gains triggered by OS through various channels. These include cost savings from free access to scientific papers and data, time savings resulting from enhanced efficiency and reduced duplication of efforts, and lower storage costs achieved through centralised or shared data repositories. | Most developed with a [causal reasoning framework](../0_causality/open_data_cost_savings.qmd) presented. |
| Innovation Output | Medium-term | This indicator measures the extent to which OS practices contribute to the development of new products, services, technologies, and patents. By enabling the broader dissemination and reuse of research outputs, OS enhances innovation opportunities across the scientific community and industry. | Moderately developed |
| Science-Industry Collaboration | Medium-term | This indicator assesses the degree of partnership between research institutions and industry facilitated by OS practices. Open access to publications and data sharing can drive collaboration, fostering innovation. This indicator can also be seen as an indicator of companies' innovation uptake. | Moderately developed |
| Socially Relevant Products and Processes | Medium to Long-term | This indicator highlights the creation of products and processes addressing societal needs that emerge from OS activities. By promoting transparency and inclusivity, OS supports innovations in sectors such as health, agriculture, and energy, generating both economic and social value. This indicator can be seen as a specific subset of Innovation Output. | Partially developed |
| Labour Market Impacts of OS | Long-term | Accessing OS practices, such as open databases and repositories, often necessitates specific skills for interpreting and processing open information. This indicator measures the extent to which OS influences the labour market by fostering the creation of new job roles and skill sets, thereby contributing to economic growth. This aspect is in its early stages of investigation, as it is one of the most challenging economic impacts to measure. | Early stage |
| Economic Growth of Companies | Long-term | This indicator discusses the contribution of OS to the economic growth of companies, particularly start-ups and SMEs. Access to open research outputs can enhance innovation capacity, competitiveness, and market expansion. As a long-term indicator, this requires a robust research design to properly identify OS impact, given the multitude of factors influencing company growth. | Early stage. Requires a robust research design. |