# Labour market impacts {#labour-market-impacts .unnumbered}
::: {}

## History
:::
## Description

\[Add text here\]

## Metrics

### Number of new job positions in the industry thanks to OS (e.g., FAIR expert)

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### Number of new job positions in public research thanks to OS

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### Number of new job positions in academia thanks to OS

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### Number of jobs displacements because of OS

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### Number of new start-ups/spin-offs founded thanks to OS

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

## Known correlates

\[Add text here\]

## Notes

\[Add text here\]

## References

\[Add Zotero bibliography here\]
