# Uptake of research result by industry {#uptake-of-research-result-by-industry .unnumbered}

History (please fill out in reverse chronological order, latest revision on top):

|         |               |                              |                           |
|---------|---------------|------------------------------|---------------------------|
| Version | Revision date | Revision                     | Author                    |
| 1.0     | 2023-02-07    | Finalised indicator template | T.P. Willemse, V.A. Traag |

## Description

\[Add text here\]

## Metrics

### #/%  of patents filed by the industry citing OS inputs

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### #/%  of new technologies developed by the industry using OS inputs

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### #/%  of new products or services developed by the industry using OS inputs

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

### Average increase in companies' patent portfolio value thanks to patent filed using OS inputs

\[Add text here\]

#### Measurement.

\[Add text here\]

##### Existing datasources:

###### &lt;datasource name&gt;

\[Add text here\]

##### Existing methodologies

###### &lt;methodology name&gt;

\[Add text here\]

## Known correlates

\[Add text here\]

## Notes

\[Add text here\]

## References

\[Add Zotero bibliography here\]
