---
author:
    - name: I. Grypari
      orcid: 0000-0002-7485-1591
      affiliations:
      - ref: arc
    - name: N. Manola
      orcid: 0000-0002-3477-3082
      affiliations:
      - ref: arc
    - name: H. Papageorgiou
      orcid: 0000-0002-7352-2403
      affiliations:
      - ref: arc
    - name: P. Stavropoulos
      orcid: 0000-0003-1664-6554
      affiliations:
      - ref: arc

affiliations:
- id: arc
  name: Athena Research Center
  city: Athena
  country: Greece

title: Availability of publication repositories
---


::: {}

# History

| Version | Revision date | Revision                      | Author                                                  |
|---------|---------------|-------------------------------|---------------------------------------------------------|
| 1.1     | 2023-08-28    | Draft for initial publication | I. Grypari                                              |
| 1.0     | 2023-02-12    | First draft                   | I. Grypari, N. Manola, H. Papageorgiou, P. Stavropoulos |

:::

# Description

To determine the size or volume of content within publication repositories in a specific field, country, or organization using the OpenAIRE Graph, researchers can analyze the Graph dump available on Zenodo or use OpenAIRE Explore ([explore.openaire.eu](https://explore.openaire.eu/)). It's crucial to understand that while the OpenAIRE Graph has integrated over 129,000 data sources, the data derived will strictly represent repositories integrated into the graph, subject to the quality of information those sources provide (<https://graph.openaire.eu/docs/> can be consulted)

# Metrics

### Accessibility of publications repositories

Evaluating the access model of publication repositories, specifically categorizing them as open access, subscription-based, or limited to specific users.

Usefulness:

-   Provides clarity on whether a wider audience can readily access the content of a repository or if there are restrictions.

Limitation:

- Some repositories might switch access models over time, or have hybrid models combining elements of open and subscription-based access. Measurement.

Examine each repository's documented access model. This can be achieved by querying databases that list repositories.

### Measurement

#### Datasources

OpenAIRE Graph and Directory of Open Access Repositories (DOAR) (integrated in the OpenAIRE Graph)

#### Methodologies

All repositories in both data sources are Open Access.

# Known correlates

Various factors **may** influence the availability of publication repositories in specific fields, countries, or organizations such as: research output, research funding, technological infrastructure, Open Access mandates, research collaboration, overall research infrastructure.

