---
author:
    - name: I. Grypari
      orcid: 0000-0002-7485-1591
      affiliations:
      - ref: arc
    - name: N. Manola
      orcid: 0000-0002-3477-3082
      affiliations:
      - ref: arc
    - name: H. Papageorgiou
      orcid: 0000-0002-7352-2403
      affiliations:
      - ref: arc
    - name: P. Stavropoulos
      orcid: 0000-0003-1664-6554
      affiliations:
      - ref: arc

affiliations:
- id: arc
  name: Athena Research Center
  city: Athena
  country: Greece

title: Availability of preprint repositories
---


::: {}

# History

| Version | Revision date | Revision                      | Author                                                  |
|---------|---------------|-------------------------------|---------------------------------------------------------|
| 1.1     | 2023-08-28    | Draft for initial publication | I. Grypari                                              |
| 1.0     | 2023-05-09    | First draft                   | I. Grypari, N. Manola, P. Stavropoulos, H. Papageorgiou |

:::

# Description

Description:

-   The "availability of preprint repositories" indicator measures the availability and accessibility of preprint repositories that are available to researchers in a particular level of interest such as field, country or organization.

Usefulness:

-   The "availability of preprint repositories" indicator provides insight into the infrastructure and resources available to researchers for sharing their work as preprints.
-   It can help to identify areas where preprint repositories are lacking or where access to these repositories is limited, potentially hindering the adoption of preprinting practices.
-   This indicator can also be used to assess the impact of preprint repositories on scholarly communication and to identify areas where additional resources and support may be needed.

Limitations:

-   Not all fields or research areas may have a culture of preprinting, which can affect the applicability of the indicator in different contexts.
-   There may be good preprint practices in general repositories (such as Zenodo) that would not be identifiable via this indicator.

# Metrics

## Number of preprint repositories

Description:

-   The "number of preprint repositories" indicator measures the quantity of preprint repositories available to researchers in a particular field, country, organization, etc.

Usefulness:

-   Provides a straightforward measure of repository availability.

Limitations:

-   Does not account for the quality or size of repositories .

### Measurement

Count

#### Datasources

##### ASAPbio

ASAPbio maintains a list of preprint repositories, available from <https://asapbio.org/preprint-servers>.

## Quality of preprint repositories

Evaluating pre-print repositories based on predetermined standards encompassing metadata consistency, user interface, search functionalities, etc.

Usefulness:

-   Differentiates repositories by the reliability and efficiency of their content and platform.

Limitation:

- Quality standards can be subjective; high quality in one domain might not be viewed as such in another.Measurement.

Use established repository ranking or rating systems, if available. Alternatively, develop a criteria checklist and review each repository against it.

## Size of pre-print repositories

Assessing the volume of content or number of publications each repository holds.

Usefulness:

- Differentiates repositories by the reliability and efficiency of their content and platform.

Limitation:

- Size does always correlate with relevance or quality of content, for example in terms of document types. Measurement.

Directly query the repository (if it offers such statistics) or query data bases that aggregate repositories.

### Measurement

#### Datasources

##### OpenAIRE Graph

#### Methodologies

To determine the size or volume of content within specific pre-print repositories in a field, country, or organization using the OpenAIRE Graph, researchers can analyze the Graph dump available on Zenodo or browse OpenAIRE EXPLORE (explore.openaire.eu). It's crucial to understand that while the OpenAIRE Graph has integrated over 129,000 data sources, the data derived will strictly represent repositories integrated into the graph, subject to the quality of information those sources provide (https://graph.openaire.eu/docs/ can be consulted)

## Accessibility of pre-print repositories

Evaluating the access model of publication repositories, specifically categorizing them as open access, subscription-based, or limited to specific users.

Usefulness:

-   Provides clarity on whether a wider audience can readily access the content of a repository or if there are restrictions.

Limitation:

- Some repositories might switch access models over time, or have hybrid models combining elements of open and subscription-based access. Measurement.

Examine each repository's documented access model. This can be achieved by querying databases that list repositories.

### Measurement

#### Datasources

OpenAIRE Graph and Directory of Open Access Repositories (DOAR) (integrated in the OpenAIRE Graph)

##### Methodologies

All repositories in both data sources are Open Access.

# Operationalization in Case Studies

## PathOS Case Studies

This indicator has been operationalized in the following case studies:
- French Open Access Infrastructure

Further details are available in Deliverable D3.3 of PathOS, accessible through the [PathOS Zenodo community](https://zenodo.org/communities/pathos/records?q=&l=list&p=1&s=10&sort=newest).

# Known correlates

The availability of preprint repositories **may** correlate with specific fields of study, given that certain scientific disciplines are more inclined to use preprints than others. Furthermore, regional or national open science policies, funding opportunities, and research culture can also influence the presence or absence of preprint repositories in a particular country or region.

