on:
  push:
    branches: [main,athenarc-deploy]
  # pull_request:
  #   branches: [main,athenarc-deploy]
  # to be able to trigger a manual build
  #workflow_dispatch:

name: Render indicator handbook

jobs:

  build_deploy:
    runs-on: ubuntu-latest
    if: github.repository	== 'PathOS-project/indicator_handbook'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render quarto project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Install pagemerger
        run: |
          curl -OL https://github.com/tymbaca/pagemerger/releases/download/v1.0.0/pagemerger_1.0-1_amd64.deb
          sudo dpkg -i pagemerger_1.0-1_amd64.deb
          sudo apt-get update
          sudo apt-get install -y aspnetcore-runtime-7.0
          sudo chmod 755 /usr/local/bin/pagemerger

      - name: Merge cover page with rendered docx
        run: |
          pagemerger out.docx etc/cover.docx _book/Open-Science-Indicator-Handbook.docx
          mv out.docx _book/Open-Science-Indicator-Handbook.docx

      - uses: athenarc/actions-docker-build-push@master
        id: docker_build
        with:
          DOCKER_REGISTRY: "pathos.docker.imsi.athenarc.gr"
          DOCKER_REPO: "indicator_handbook"
          DOCKER_USER: "builder"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"

      - uses: athenarc/actions-docker-compose-deploy@master
        id: docker_deploy
        with:
          AUTH_TOKEN: "${{ secrets.DEPLOY_AUTH_TOKEN }}"
          USE_PULL_REPO: "false"
          DEPLOY_URL: "https://delphinus.imsi.athenarc.gr/docker-compose-deploy/deploy"
          IMAGES: "${{ steps.docker_build.outputs.images }}"